(()=>{
'use strict';
if(window.__ZR_ADMIN_RESERVATION_CLEANUP_CANCEL_V1)return;
window.__ZR_ADMIN_RESERVATION_CLEANUP_CANCEL_V1=true;

const FV='12.17.1';
const STAFF_EMAIL='zoolung09@zoolungzoolung.com';
const KEY='zr_bookings';
const PAGE_SIZE=8;
const BUSY=new Set();
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,'0');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let F=null,db=null,auth=null,page=1,selected=new Set(),installed=false;

function toast(msg){try{if(typeof window.toast==='function')return window.toast(msg)}catch{}alert(msg)}
function today(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function monthsAgo(dateStr,months){const d=new Date(String(dateStr)+'T12:00:00');if(Number.isNaN(d.getTime()))return'';const day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()-months);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function dateLabel(v){if(!v)return'-';const d=new Date(String(v)+'T12:00:00');if(Number.isNaN(d.getTime()))return String(v);return `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`}
function cancelDateKey(b){
  const v=b?.cancelledAt;if(!v)return'';
  if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}/.test(v))return v.slice(0,10);
  const d=v?.toDate?.()||((v&&typeof v.seconds==='number')?new Date(v.seconds*1000):new Date(v));
  if(Number.isNaN(d?.getTime?.()))return'';
  return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
}
function stampLabel(v){if(!v)return'-';const d=v?.toDate?.()||((v&&typeof v.seconds==='number')?new Date(v.seconds*1000):new Date(v));if(Number.isNaN(d?.getTime?.()))return'-';return `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`}
function cutoff(){return monthsAgo(today(),6)}
function eligible(b){const d=cancelDateKey(b);return String(b?.status||'')==='cancelled'&&!!d&&d<=cutoff()}
function bookings(){try{const list=typeof window.bookings==='function'?window.bookings():JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(list)?list.filter(b=>b&&!b.__availabilityOnly&&!b.__legacyLocal):[]}catch{return[]}}
function filters(){return {start:$('zrCancelCleanupStart')?.value||'',end:$('zrCancelCleanupEnd')?.value||''}}
function rows(){const f=filters();return bookings().filter(eligible).filter(b=>{const d=cancelDateKey(b);return !(f.start&&d<f.start)&&!(f.end&&d>f.end)}).sort((a,b)=>cancelDateKey(b).localeCompare(cancelDateKey(a))||String(a.orgName||'').localeCompare(String(b.orgName||''),'ko'))}
function phoneLast4(b){const raw=b?.contact||b?.phone||b?.phoneNumber||b?.contactPhone||b?.managerPhone||b?.tel||b?.mobile||'';const digits=String(raw).replace(/\D/g,'');return digits.length>=4?digits.slice(-4):'확인 불가'}
function pageNumbers(current,pages){if(pages<=7)return Array.from({length:pages},(_,i)=>i+1);const keep=new Set([1,pages,current-1,current,current+1]),valid=[...keep].filter(n=>n>=1&&n<=pages).sort((a,b)=>a-b),out=[];let prev=0;for(const n of valid){if(prev&&n-prev>1)out.push('…');out.push(n);prev=n}return out}
function pagerHtml(current,pages){const nums=pageNumbers(current,pages).map(n=>n==='…'?'<span class="zr-cleanup-page-gap">…</span>':`<button type="button" class="${n===current?'btn-primary':'btn-soft'}" data-zr-cancel-cleanup-page="${n}" ${n===current?'aria-current="page"':''}>${n}</button>`).join('');return `<div class="zr-cleanup-pagination"><button type="button" class="btn-soft" data-zr-cancel-cleanup-page="prev" ${current<=1?'disabled':''}>이전</button>${nums}<button type="button" class="btn-soft" data-zr-cancel-cleanup-page="next" ${current>=pages?'disabled':''}>다음</button></div>`}
function cardHtml(b){const id=String(b.id),paid=Number(b.paidCount||0),chap=Number(b.chaperoneCount||0),checked=selected.has(id),cancelBy=String(b.cancelledBy||'')==='customer'?'고객 취소':String(b.cancelledBy||'')==='admin'?'관리자 취소':'취소';return `<article class="zr-cleanup-card" data-cancel-booking="${esc(id)}"><label class="zr-cleanup-check"><input type="checkbox" data-zr-cancel-cleanup-select="${esc(id)}" ${checked?'checked':''}><span></span></label><div class="zr-cleanup-main"><div class="zr-cleanup-title"><b>${esc(b.orgName||'단체명 미입력')}</b><span>방문 ${esc(dateLabel(b.date))}</span></div><div class="zr-cleanup-meta"><span>취소일 ${esc(stampLabel(b.cancelledAt))}</span><span>${esc(cancelBy)}</span><span>유료 ${paid}명</span><span>인솔 ${chap}명</span><span>예약번호 ${esc(id)}</span></div></div><button type="button" class="btn-gray zr-cleanup-danger" data-zr-cancel-cleanup-one="${esc(id)}">정리</button></article>`}
function render(){const all=rows(),pages=Math.max(1,Math.ceil(all.length/PAGE_SIZE));page=Math.min(Math.max(1,page),pages);const ids=new Set(all.map(x=>String(x.id)));selected=new Set([...selected].filter(id=>ids.has(id)));const start=(page-1)*PAGE_SIZE,shown=all.slice(start,start+PAGE_SIZE);if($('zrCancelCleanupCount'))$('zrCancelCleanupCount').textContent=`정리 대상 ${all.length}건 · 선택 ${selected.size}건`;if($('zrCancelCleanupCutoff'))$('zrCancelCleanupCutoff').textContent=`${dateLabel(cutoff())} 이전 취소`;if($('zrCancelCleanupList'))$('zrCancelCleanupList').innerHTML=shown.length?shown.map(cardHtml).join(''):'<div class="zr-cleanup-empty"><b>현재 정리 가능한 취소 예약이 없습니다.</b><span>취소일 기준 6개월이 지난 취소 예약만 표시합니다.</span></div>';if($('zrCancelCleanupPager'))$('zrCancelCleanupPager').innerHTML=pagerHtml(page,pages);if($('zrCancelCleanupSelected'))$('zrCancelCleanupSelected').disabled=!selected.size;if($('zrCancelCleanupAll'))$('zrCancelCleanupAll').disabled=!all.length;const pageIds=shown.map(x=>String(x.id)),allChecked=pageIds.length&&pageIds.every(id=>selected.has(id));if($('zrCancelCleanupSelectPage')){$('zrCancelCleanupSelectPage').checked=!!allChecked;$('zrCancelCleanupSelectPage').disabled=!pageIds.length}}
function setPage(next){const pages=Math.max(1,Math.ceil(rows().length/PAGE_SIZE));if(next==='prev')page=Math.max(1,page-1);else if(next==='next')page=Math.min(pages,page+1);else page=Math.min(pages,Math.max(1,Number(next)||1));render();$('zrCancelCleanupList')?.scrollIntoView?.({block:'start'})}
function bridge(){return window.zrReservationFirebase||null}
function isStaff(){const z=bridge();return !!z?.isStaff?.()&&String(z.auth?.currentUser?.email||'').toLowerCase()===STAFF_EMAIL.toLowerCase()}
async function ensureFirebase(){if(F&&db&&auth)return true;const z=bridge();if(!z?.db||!z?.auth)return false;F=await import(`https://www.gstatic.com/firebasejs/${FV}/firebase-firestore.js`);db=z.db;auth=z.auth;return true}
async function refreshConnection(){if(!await ensureFirebase())throw Object.assign(new Error('Firebase bridge not ready'),{code:'bridge-not-ready'});if(!isStaff())throw Object.assign(new Error('관리자 Firebase 로그인이 아닙니다.'),{code:'staff-auth-required'});try{await auth.currentUser?.getIdToken?.(true)}catch(e){console.debug('cancel cleanup token refresh',e)}try{await F.enableNetwork(db)}catch(e){console.debug('cancel cleanup enable network',e)}}
function errorLabel(e){const code=String(e?.code||'').replace(/^firestore\//,'');const msg=String(e?.message||'').replace(/\s+/g,' ').trim();return code?`${code}${msg?` · ${msg.slice(0,90)}`:''}`:(msg||'unknown-error')}
function preview(items){const limit=12,shown=items.slice(0,limit),lines=shown.map((b,i)=>`${i+1}. ${String(b?.orgName||'단체명 미입력')}\n   방문 ${dateLabel(b?.date)} · 취소일 ${dateLabel(cancelDateKey(b))}\n   예약번호 ${String(b?.id||'-')} · 연락처 뒤 4자리 ${phoneLast4(b)}`);if(items.length>limit)lines.push(`외 ${items.length-limit}건`);return lines.join('\n')}
function confirmCleanup(items){if(!confirm(`${items.length}건의 취소 예약을 영구 정리합니다.\n취소일 기준 6개월이 지난 예약만 대상입니다.\n\n계속하시겠습니까?`))return false;return confirm(`마지막 확인입니다. 삭제할 취소 예약이 맞는지 확인해주세요.\n\n${preview(items)}\n\n예약 본문과 예약 가능 데이터는 삭제되며 되돌릴 수 없습니다.\n연락처와 취소 사유는 정리 내역에 저장하지 않습니다.\n\n${items.length}건을 정리할까요?`)}
function localRemove(ids){const set=new Set(ids.map(String)),next=bookings().filter(b=>!set.has(String(b.id)));try{if(typeof window.setStore==='function')window.setStore(KEY,next)}catch(e){console.debug('cancel cleanup local sync',e)}}
function setBusy(el,busy){if(!el)return;if(busy){el.dataset.zrCancelCleanupBusyText=el.textContent||'';el.disabled=true;el.textContent='정리 중…'}else{el.disabled=false;if(el.dataset.zrCancelCleanupBusyText)el.textContent=el.dataset.zrCancelCleanupBusyText;delete el.dataset.zrCancelCleanupBusyText}}
function buildBatch(chunk){const batch=F.writeBatch(db),iso=new Date().toISOString(),date=iso.slice(0,10),cleanedBy=String(auth.currentUser?.email||STAFF_EMAIL);for(const b of chunk){const id=String(b.id),history={archived:true,archiveType:'reservationCleanup',reservationId:id,orgName:String(b.orgName||''),visitDate:String(b.date||''),paidCount:Number(b.paidCount||0),chaperoneCount:Number(b.chaperoneCount||0),cleanupMode:'취소 정리',cleanupDate:date,cleanupIso:iso,cleanupAt:F.serverTimestamp(),cleanedBy};batch.set(F.doc(db,'scheduleGroups',id),history);batch.delete(F.doc(db,'reservations',id));batch.delete(F.doc(db,'reservationAvailability',id))}return batch}
async function execute(items,button){const valid=(Array.isArray(items)?items:[]).filter(eligible).filter(b=>!BUSY.has(String(b.id)));if(!valid.length)return toast('정리 가능한 취소 예약이 없습니다.');if(!confirmCleanup(valid))return;const ids=valid.map(b=>String(b.id));ids.forEach(id=>BUSY.add(id));setBusy(button,true);try{await refreshConnection();const chunks=[];for(let i=0;i<valid.length;i+=100)chunks.push(valid.slice(i,i+100));for(const chunk of chunks)await buildBatch(chunk).commit();localRemove(ids);selected.clear();page=1;render();$('zrCleanupApply')?.click?.();toast(`${valid.length}건의 취소 예약을 정리했습니다.`)}catch(e){console.error('cancel reservation cleanup',e);toast(`취소 예약 정리에 실패했습니다.\n오류: ${errorLabel(e)}\n데이터는 화면에서 임의로 삭제하지 않았습니다.`)}finally{ids.forEach(id=>BUSY.delete(id));setBusy(button,false)}}
function showCancel(){const panel=$('zrCancelCleanupPanel');if(!panel)return;$('zrCleanupPanel')?.classList.add('hidden');$('zrCleanupHistoryPanel')?.classList.add('hidden');panel.classList.remove('hidden');$('zrCleanupSubtab')?.classList.remove('btn-primary');$('zrCleanupSubtab')?.classList.add('btn-gray');$('zrCleanupHistorySubtab')?.classList.remove('btn-primary');$('zrCleanupHistorySubtab')?.classList.add('btn-gray');$('zrCancelCleanupSubtab')?.classList.remove('btn-gray');$('zrCancelCleanupSubtab')?.classList.add('btn-primary');render()}
function hideCancel(){const panel=$('zrCancelCleanupPanel');panel?.classList.add('hidden');const btn=$('zrCancelCleanupSubtab');btn?.classList.remove('btn-primary');btn?.classList.add('btn-gray')}
function installStyle(){if($('zrCancelCleanupStyleV1'))return;const s=document.createElement('style');s.id='zrCancelCleanupStyleV1';s.textContent=`
#tab-cleanup .zr-cleanup-selectall,#tab-cleanup .zr-cancel-cleanup-selectall{display:inline-flex!important;flex-direction:row!important;flex-wrap:nowrap!important;align-items:center!important;gap:8px!important;white-space:nowrap!important;min-width:max-content!important;width:auto!important;line-height:1.2!important}#tab-cleanup .zr-cleanup-selectall input,#tab-cleanup .zr-cancel-cleanup-selectall input{flex:0 0 auto!important;width:18px!important;height:18px!important;margin:0!important}#tab-cleanup [data-zr-cleanup-one],#zrCleanupSelected,#zrCleanupAllResult,#tab-cleanup [data-zr-cancel-cleanup-one],#zrCancelCleanupSelected,#zrCancelCleanupAll{background:#fff1f1!important;border-color:#e8bcbc!important;color:#9a4141!important}#tab-cleanup [data-zr-cleanup-one]:hover,#zrCleanupSelected:hover,#zrCleanupAllResult:hover,#tab-cleanup [data-zr-cancel-cleanup-one]:hover,#zrCancelCleanupSelected:hover,#zrCancelCleanupAll:hover{background:#ffe7e7!important;border-color:#dca6a6!important}#tab-cleanup .zr-cleanup-danger:disabled,#zrCleanupSelected:disabled,#zrCleanupAllResult:disabled,#zrCancelCleanupSelected:disabled,#zrCancelCleanupAll:disabled{opacity:.45!important}#zrCancelCleanupPanel .zr-cleanup-help b{color:#8d4343}@media(max-width:720px){#zrCleanupInnerTabs{grid-template-columns:repeat(3,minmax(0,1fr))!important}#zrCleanupInnerTabs button{padding:0 8px!important;font-size:12px!important}#tab-cleanup .zr-cleanup-selectall,#tab-cleanup .zr-cancel-cleanup-selectall{min-width:0!important;width:100%!important}.zr-cleanup-toolbuttons{grid-template-columns:1fr 1fr!important}}
`;document.head.appendChild(s)}
function install(){if(installed)return true;const tabs=$('zrCleanupInnerTabs'),cleanupPanel=$('zrCleanupPanel'),historyPanel=$('zrCleanupHistoryPanel');if(!tabs||!cleanupPanel||!historyPanel)return false;installStyle();let sub=$('zrCancelCleanupSubtab');if(!sub){sub=document.createElement('button');sub.type='button';sub.id='zrCancelCleanupSubtab';sub.className='btn-gray';sub.textContent='취소 정리';$('zrCleanupHistorySubtab')?.before(sub)}let panel=$('zrCancelCleanupPanel');if(!panel){panel=document.createElement('div');panel.className='zr-cleanup-panel hidden';panel.id='zrCancelCleanupPanel';panel.innerHTML=`<div class="zr-cleanup-head"><div><h2>취소 예약 정리</h2><div class="zr-cleanup-help">취소일 기준 6개월이 지난 취소 예약을 영구 정리합니다.<br>정리 후 고객/관리자 취소내역에서도 해당 예약은 사라지며, 최소 정리 기록만 남습니다.</div></div><span id="zrCancelCleanupCount">정리 대상 0건 · 선택 0건</span></div><div class="zr-cleanup-filters"><div class="zr-cleanup-field"><label>취소일 시작</label><input type="date" id="zrCancelCleanupStart"></div><div class="zr-cleanup-field"><label>취소일 종료</label><input type="date" id="zrCancelCleanupEnd"></div><button type="button" class="btn-primary" id="zrCancelCleanupApply">조회하기</button></div><div class="zr-cleanup-help">정리 가능 기준: <b id="zrCancelCleanupCutoff"></b></div><div class="zr-cleanup-tools"><label class="zr-cancel-cleanup-selectall"><input type="checkbox" id="zrCancelCleanupSelectPage"> 현재 페이지 전체 선택</label><div class="zr-cleanup-toolbuttons"><button type="button" class="btn-gray zr-cleanup-danger" id="zrCancelCleanupSelected" disabled>선택 정리</button><button type="button" class="btn-soft zr-cleanup-danger" id="zrCancelCleanupAll" disabled>조회 결과 전체 정리</button></div></div><div class="zr-cleanup-list" id="zrCancelCleanupList"></div><div id="zrCancelCleanupPager"></div>`;historyPanel.before(panel)}
sub.onclick=showCancel;$('zrCleanupSubtab')?.addEventListener('click',hideCancel);$('zrCleanupHistorySubtab')?.addEventListener('click',hideCancel);$('zrCancelCleanupApply').onclick=()=>{page=1;selected.clear();render()};$('zrCancelCleanupSelectPage').onchange=e=>{const all=rows(),start=(page-1)*PAGE_SIZE,ids=all.slice(start,start+PAGE_SIZE).map(x=>String(x.id));ids.forEach(id=>e.target.checked?selected.add(id):selected.delete(id));render()};$('zrCancelCleanupSelected').onclick=e=>execute(rows().filter(b=>selected.has(String(b.id))),e.currentTarget);$('zrCancelCleanupAll').onclick=e=>execute(rows(),e.currentTarget);$('zrCancelCleanupList').onclick=e=>{const btn=e.target?.closest?.('[data-zr-cancel-cleanup-one]');if(!btn)return;const b=rows().find(x=>String(x.id)===String(btn.dataset.zrCancelCleanupOne));if(b)execute([b],btn)};$('zrCancelCleanupList').onchange=e=>{const box=e.target?.closest?.('[data-zr-cancel-cleanup-select]');if(!box)return;const id=String(box.dataset.zrCancelCleanupSelect||'');box.checked?selected.add(id):selected.delete(id);render()};$('zrCancelCleanupPager').onclick=e=>{const b=e.target?.closest?.('[data-zr-cancel-cleanup-page]');if(b&&!b.disabled)setPage(b.dataset.zrCancelCleanupPage)};window.addEventListener('storage',e=>{if(e.key===KEY&&!$('zrCancelCleanupPanel')?.classList.contains('hidden'))render()});installed=true;render();return true}
function boot(){if(install())return;let tries=0;const timer=setInterval(()=>{if(install()||++tries>100)clearInterval(timer)},120)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();