(()=>{
'use strict';
const FV='12.17.1',EMAIL='zoolung09@zoolungzoolung.com',START=600,MAX=1080,SLOT=15;
const LABEL={f4:'4F 베이직',f5:'5F 워터가든',meal:'식사',play:'놀이터'},CLS={f4:'zrsc-f4',f5:'zrsc-f5',meal:'zrsc-meal',play:'zrsc-play'};
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0'),tm=m=>pad(Math.floor(m/60))+':'+pad(m%60);
const mn=t=>{if(!t)return null;const [h,m]=String(t).split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const add=(t,d)=>mn(t)==null?'':tm(mn(t)+Number(d||0));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const shift=(s,n)=>{const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const toast=s=>{try{window.toast?.(s)}catch{}};
let F,db,auth,date=today(),unsub,remote=new Map(),installed=false;
function bookingsForDate(){try{return window.bookings().filter(b=>b&&!b.__availabilityOnly&&b.status==='confirmed'&&b.date===date).sort((a,b)=>String(a.entryTime||'99:99').localeCompare(String(b.entryTime||'99:99'))||String(a.orgName||'').localeCompare(String(b.orgName||''),'ko'))}catch{return[]}}
function mealText(b){return ({lunchbox:'도시락',cafe:'카페주문',none:'식사없음'})[b.mealType]||'식사없음'}
function cafeText(b){return (b.cafe?.items||[]).map(x=>`${x.name} × ${x.qty}`).join(' / ')}
function seg(type,start,end){return start&&end?{id:`${type}_${Math.random().toString(36).slice(2,7)}`,type,start,end}:null}
function find(d,t){return (d?.segments||[]).find(s=>s.type===t)||null}
function def(b,t){if(t==='meal'&&b.mealType!=='none'&&b.mealStart)return seg(t,b.mealStart,b.mealEnd||add(b.mealStart,b.mealDuration));if(t==='play'&&b.playUse!=='no'&&b.playStart)return seg(t,b.playStart,b.playEnd||add(b.playStart,b.playDuration));return null}
function managed(b,d){return {f4:find(d,'f4'),f5:find(d,'f5'),meal:find(d,'meal')||def(b,'meal'),play:find(d,'play')||def(b,'play')}}
function preserved(d){return (d?.segments||[]).filter(s=>!['f4','f5','meal','play'].includes(s.type))}
function axisFor(rows){let vals=[900];rows.forEach(({b,d})=>{const e=mn(b.exitTime);if(e!=null)vals.push(e);(d?.segments||[]).forEach(s=>{const z=mn(s.end);if(z!=null)vals.push(z)})});let end=Math.max(900,Math.ceil(Math.max(...vals)/60)*60);return {start:START,end:Math.min(MAX,end)}}
function pct(t,a){const m=mn(t);return m==null?0:Math.max(0,Math.min(100,(m-a.start)/(a.end-a.start)*100))}
function ruler(a){const span=a.end-a.start,step=span>360?60:30;let h=`<div class="zrsc-grid" style="background-size:${SLOT/span*100}% 100%"></div>`;for(let m=a.start;m<=a.end;m+=step)h+=`<span class="zrsc-tick" style="left:${(m-a.start)/span*100}%">${tm(m)}</span>`;return h}
function segHtml(s,a){if(!s?.start||!s?.end)return'';const w=Math.max(1,pct(s.end,a)-pct(s.start,a));return `<div class="zrsc-seg ${CLS[s.type]||''}" style="left:${pct(s.start,a)}%;width:${w}%"><b>${LABEL[s.type]||s.type}</b>${w>=8?`<small>${s.start}~${s.end}</small>`:''}</div>`}
function opts(v,maxTime){const max=Math.min(MAX,mn(maxTime)??MAX);let h='<option value="">선택</option>';for(let m=START;m<=max;m+=SLOT){const t=tm(m);h+=`<option value="${t}" ${t===v?'selected':''}>${t}</option>`}return h}
function overlap(a,b){return mn(a.start)<mn(b.end)&&mn(b.start)<mn(a.end)}
function validate(ss,exit){for(const s of ss){if(!s.start||!s.end)return `${LABEL[s.type]} 시작·종료 시간을 모두 선택해주세요.`;if(mn(s.end)<=mn(s.start))return `${LABEL[s.type]} 종료시간은 시작시간보다 늦어야 합니다.`;if(mn(exit)!=null&&mn(s.end)>mn(exit))return `${LABEL[s.type]} 종료시간은 예약 퇴장시간(${exit})을 넘을 수 없습니다.`}const a=[...ss].sort((x,y)=>mn(x.start)-mn(y.start));for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)if(overlap(a[i],a[j]))return `${LABEL[a[i].type]}과 ${LABEL[a[j].type]} 시간이 겹칩니다.`;return''}
function collect(card,b,d){const q=f=>card.querySelector(`[data-field="${f}"]`)?.value||'',map={f4:[q('f4s'),q('f4e')],f5:[q('f5s'),q('f5e')],meal:[q('meals'),q('meale')],play:[q('plays'),q('playe')]},ss=[];for(const t of ['f4','f5','meal','play']){const [s,e]=map[t];if(s||e)ss.push({id:`${t}_${b.id}`,type:t,start:s,end:e})}return {segments:ss,err:validate(ss,b.exitTime)}}
function style(){if($('zrScheduleStyle'))return;const s=document.createElement('style');s.id='zrScheduleStyle';s.textContent=`#tab-schedule .zrsc-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:12px}#tab-schedule .zrsc-toolbar input{width:auto;min-width:150px}#tab-schedule .zrsc-status{margin-left:auto;font-size:12px;padding:6px 9px;border-radius:999px;border:1px solid var(--line);background:#f3f5f3;color:var(--muted);font-weight:800}#tab-schedule .zrsc-status.ok{color:#2f6b4f;background:#e9f3ed;border-color:#c6decf}#tab-schedule .zrsc-status.err{color:#a33b3b;background:#fbecec;border-color:#e8c6c6}#tab-schedule .zrsc-ruler,#tab-schedule .zrsc-line{position:relative;height:58px;margin-top:9px;border:1px solid var(--line);border-radius:11px;background:#fff;overflow:hidden}#tab-schedule .zrsc-ruler{height:32px;border:none;background:transparent;overflow:visible;margin:4px 0 2px}#tab-schedule .zrsc-grid{position:absolute;inset:0;background-image:linear-gradient(to right,rgba(47,107,79,.10) 1px,transparent 1px)}#tab-schedule .zrsc-tick{position:absolute;top:6px;transform:translateX(-50%);font-size:11px;color:var(--muted);white-space:nowrap}#tab-schedule .zrsc-card{margin-top:12px;border:1px solid var(--line);border-radius:15px;padding:14px;background:#fff}#tab-schedule .zrsc-head{display:flex;gap:7px;align-items:center;flex-wrap:wrap}#tab-schedule .zrsc-org{font-weight:900;font-size:17px;margin-right:auto}#tab-schedule .zrsc-tag{font-size:11px;padding:5px 8px;border-radius:999px;background:#f2f5f2;border:1px solid var(--line)}#tab-schedule .zrsc-tag.pub{background:#e9f3ed;border-color:#c6decf;color:#2f6b4f;font-weight:800}#tab-schedule .zrsc-edit{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:11px;align-items:end}#tab-schedule .zrsc-edit label{font-size:11px;font-weight:800;color:var(--muted);display:block;margin-bottom:4px}#tab-schedule .zrsc-edit select{width:100%;padding:9px 6px}#tab-schedule .zrsc-actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:8px;align-items:center;flex-wrap:wrap;margin-top:2px}#tab-schedule .zrsc-error{margin-right:auto;color:#b23838;font-size:12px;font-weight:800}#tab-schedule .zrsc-seg{position:absolute;top:4px;bottom:4px;border-radius:8px;padding:5px 7px;box-sizing:border-box;overflow:hidden;font-size:11px;z-index:2}#tab-schedule .zrsc-seg b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#tab-schedule .zrsc-seg small{font-size:9px;white-space:nowrap}#tab-schedule .zrsc-f4{background:#f8d7bf}#tab-schedule .zrsc-f5{background:#cfe7f7}#tab-schedule .zrsc-meal{background:#fff0a8}#tab-schedule .zrsc-play{background:#d8efc9}#tab-schedule .zrsc-empty{text-align:center;padding:30px;color:var(--muted)}@media(max-width:700px){#tab-schedule .zrsc-edit{grid-template-columns:1fr 1fr}#tab-schedule .zrsc-line{height:52px}}`;document.head.appendChild(s)}
function install(){if(installed)return true;const tabs=document.querySelector('#adminView .admin-tabs');if(!tabs)return false;style();const btn=document.createElement('button');btn.id='zrScheduleTabBtn';btn.className='btn-gray';btn.textContent='스케줄 관리';tabs.appendChild(btn);const sec=document.createElement('section');sec.id='tab-schedule';sec.className='hidden';sec.innerHTML=`<div class="card" style="margin-top:14px"><div class="row"><div><h2 style="margin:0 0 4px">스케줄 관리</h2><div class="help">시간 변경 후 <b>스케줄 반영</b>을 눌러야 현장에 적용됩니다. 엑셀은 반영된 스케줄 기준입니다.</div></div><button class="btn-soft" id="zrscExcel">엑셀 내려받기</button></div><div class="zrsc-toolbar"><button class="btn-soft" id="zrscPrev">‹</button><input type="date" id="zrscDate"><button class="btn-soft" id="zrscNext">›</button><button class="btn-gray" id="zrscToday">오늘</button><span class="zrsc-status" id="zrscStatus">DB 연결 대기</span></div><div class="zrsc-ruler" id="zrscRuler"></div><div id="zrscList"></div></div>`;document.querySelector('#adminView').appendChild(sec);btn.onclick=openTab;document.querySelectorAll('#adminView .admin-tabs button').forEach(x=>{if(x!==btn)x.addEventListener('click',()=>sec.classList.add('hidden'))});$('zrscDate').value=date;$('zrscDate').onchange=()=>setDate($('zrscDate').value);$('zrscPrev').onclick=()=>setDate(shift(date,-1));$('zrscNext').onclick=()=>setDate(shift(date,1));$('zrscToday').onclick=()=>setDate(today());installed=true;return true}
function openTab(){document.querySelectorAll('#adminView section[id^="tab-"]').forEach(s=>s.classList.add('hidden'));document.querySelectorAll('#adminView .admin-tabs button').forEach(b=>b.className='btn-gray');$('tab-schedule').classList.remove('hidden');$('zrScheduleTabBtn').className='btn-primary';$('zrscDate').value=date;render();listen()}
function setDate(d){if(!d)return;date=d;$('zrscDate').value=d;render();listen()}
function render(){if(!$('zrscList'))return;const bs=bookingsForDate(),rows=bs.map(b=>({b,d:remote.get(String(b.id))||null})),axis=axisFor(rows);$('zrscRuler').innerHTML=ruler(axis);if(!rows.length){$('zrscList').innerHTML='<div class="zrsc-empty">이 날짜에 확정된 예약이 없습니다.</div>';return}$('zrscList').innerHTML=rows.map(({b,d})=>{const m=managed(b,d),pv=[m.f4,m.f5,m.meal,m.play].filter(Boolean).sort((x,y)=>String(x.start).localeCompare(String(y.start))).map(s=>segHtml(s,axis)).join(''),pub=!!(d?.published||b.schedulePublished),max=b.exitTime||'18:00',meal=b.mealType!=='none'?`<div><label>식사 시작</label><select data-field="meals">${opts(m.meal?.start||'',max)}</select></div><div><label>식사 종료</label><select data-field="meale">${opts(m.meal?.end||'',max)}</select></div>`:'',play=b.playUse!=='no'?`<div><label>놀이터 시작</label><select data-field="plays">${opts(m.play?.start||'',max)}</select></div><div><label>놀이터 종료</label><select data-field="playe">${opts(m.play?.end||'',max)}</select></div>`:'';return `<div class="zrsc-card" data-booking="${esc(b.id)}"><div class="zrsc-head"><div class="zrsc-org">${esc(b.orgName)}</div><span class="zrsc-tag">${Number(b.paidCount||0)}(${Number(b.chaperoneCount||0)})명</span><span class="zrsc-tag">예약 ${esc(b.entryTime)}~${esc(b.exitTime)}</span><span class="zrsc-tag">${esc(mealText(b))}</span>${b.playUse!=='no'?'<span class="zrsc-tag">놀이터 이용</span>':''}${pub?'<span class="zrsc-tag pub">✓ 고객 노출 중</span>':''}</div><div class="zrsc-line" data-preview><div class="zrsc-grid" style="background-size:${SLOT/(axis.end-axis.start)*100}% 100%"></div>${pv}</div><div class="zrsc-edit"><div><label>4F 시작</label><select data-field="f4s">${opts(m.f4?.start||'',max)}</select></div><div><label>4F 종료</label><select data-field="f4e">${opts(m.f4?.end||'',max)}</select></div><div><label>5F 시작</label><select data-field="f5s">${opts(m.f5?.start||'',max)}</select></div><div><label>5F 종료</label><select data-field="f5e">${opts(m.f5?.end||'',max)}</select></div>${meal}${play}<div class="zrsc-actions"><span class="zrsc-error" data-error></span><button class="btn-primary" data-apply="${esc(b.id)}">스케줄 반영</button>${pub?'<button class="btn-gray" disabled>✓ 스케줄 확정됨</button>':`<button class="btn-soft" data-publish="${esc(b.id)}">스케줄 확정</button>`}</div></div></div>`}).join('');document.querySelectorAll('#tab-schedule .zrsc-card').forEach(card=>{const id=card.dataset.booking,b=bs.find(x=>String(x.id)===String(id)),d=remote.get(String(id))||null;if(!b)return;card.querySelectorAll('select').forEach(s=>s.onchange=()=>preview(card,b,d,axis));card.querySelector('[data-apply]')?.addEventListener('click',e=>applySchedule(id,e.currentTarget,false));card.querySelector('[data-publish]')?.addEventListener('click',e=>applySchedule(id,e.currentTarget,true));preview(card,b,d,axis)})}
function preview(card,b,d,axis){const c=collect(card,b,d),box=card.querySelector('[data-preview]');box.innerHTML=`<div class="zrsc-grid" style="background-size:${SLOT/(axis.end-axis.start)*100}% 100%"></div>${c.segments.filter(s=>s.start&&s.end).sort((x,y)=>String(x.start).localeCompare(String(y.start))).map(s=>segHtml(s,axis)).join('')}`;card.querySelector('[data-error]').textContent=c.err||'';card.querySelector('[data-apply]').disabled=!!c.err;const p=card.querySelector('[data-publish]');if(p)p.disabled=!!c.err}
function customerData(b,ss){return {date:b.date,org:b.orgName||'',entryTime:b.entryTime||'',exitTime:b.exitTime||'',segments:ss.filter(s=>['f4','f5','meal','play'].includes(s.type)).map(s=>({type:s.type,start:s.start,end:s.end}))}}
async function applySchedule(id,btn,publish){const b=bookingsForDate().find(x=>String(x.id)===String(id));if(!b)return toast('예약 정보를 찾지 못했습니다.');if(!F||!db||!auth?.currentUser||String(auth.currentUser.email||'').toLowerCase()!==EMAIL)return toast('공용 DB 로그인 연결을 확인해주세요.');const card=btn.closest('.zrsc-card'),d=remote.get(String(id))||null,c=collect(card,b,d);if(c.err)return toast(c.err);const was=!!(d?.published||b.schedulePublished),pub=publish||was,ss=[...c.segments,...preserved(d)].sort((x,y)=>String(x.start).localeCompare(String(y.start))),patch={reservationId:String(b.id),date:b.date,org:b.orgName||'',res:Number(b.paidCount||0),tea:Number(b.chaperoneCount||0),ps:b.entryTime||'',pe:b.exitTime||'',meal:mealText(b),cafeDetail:cafeText(b),segments:ss,published:pub,updatedAt:F.serverTimestamp()};const old=btn.textContent;btn.disabled=true;btn.textContent=publish?'확정 중...':'반영 중...';try{await F.setDoc(F.doc(db,'scheduleGroups',String(b.id)),patch,{merge:true});if(pub)await F.setDoc(F.doc(db,'reservations',String(b.id)),{schedulePublished:true,customerSchedule:customerData(b,ss),schedulePublishedAt:F.serverTimestamp()},{merge:true});toast(publish?'스케줄을 확정하고 고객에게 노출했습니다.':'현장 스케줄에 반영했습니다.')}catch(e){console.error(e);toast('스케줄 반영에 실패했습니다. DB 연결을 확인해주세요.')}finally{btn.disabled=false;btn.textContent=old}}
function status(t,c=''){const e=$('zrscStatus');if(e){e.textContent=t;e.className='zrsc-status'+(c?' '+c:'')}}
function listen(){if(unsub){unsub();unsub=null}if(!F||!db||!auth?.currentUser)return status('DB 연결 대기');status('불러오는 중...');try{const q=F.query(F.collection(db,'scheduleGroups'),F.where('date','==',date));unsub=F.onSnapshot(q,s=>{remote=new Map(s.docs.map(d=>[d.id,{id:d.id,...d.data()}]));status('● 실시간 연결됨','ok');render()},e=>{console.error(e);status('DB 연결 확인 필요','err')})}catch(e){console.error(e);status('DB 연결 확인 필요','err')}}
async function initFirebase(){try{const [a,u,f]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FV}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FV}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FV}/firebase-firestore.js`)]),app=a.getApps()[0];if(!app)throw Error('Firebase app not initialized');auth=u.getAuth(app);db=f.getFirestore(app);F={...f};u.onAuthStateChanged(auth,()=>{if(!$('tab-schedule')?.classList.contains('hidden'))listen()})}catch(e){console.error(e);status('DB 연결 확인 필요','err')}}
window.zrScheduleAdminV2={get date(){return date},getRows:()=>bookingsForDate().map(b=>({b,d:remote.get(String(b.id))||null})),axisFor,managed,label:LABEL,toMin:mn,toTime:tm,slot:SLOT,start:START,max:MAX,toast};
function boot(){const t=setInterval(()=>{if(install()){clearInterval(t);initFirebase()}},300);setTimeout(()=>clearInterval(t),15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();