(()=>{
'use strict';
if(window.__ZR_CUSTOMER_VISIT_GUIDE_V19)return;
window.__ZR_CUSTOMER_VISIT_GUIDE_V19=true;

const FV='12.17.1';
const COLLECTION='customerGuides';
const DOC_ID='main';
const STAFF_EMAIL='zoolung09@zoolungzoolung.com';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>/^https?:\/\//i.test(String(u||'').trim())?String(u).trim():'';
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`;
const toast=s=>{try{window.toast?.(s)}catch{}};
const DEFAULT_GUIDE={contents:[
  {id:'guide_f4',name:'4F 베이직',duration:'',imageUrl:'',description:'4F 동물 관람 컨텐츠입니다.',enabled:true},
  {id:'guide_f5',name:'5F 워터가든',duration:'',imageUrl:'',description:'5F 워터가든 관람 컨텐츠입니다.',enabled:true},
  {id:'guide_play',name:'놀이터',duration:'',imageUrl:'',description:'예약된 이용시간에 맞춰 놀이터를 이용합니다.',enabled:true}
],notices:[
  {id:'notice_1',text:'동물 관람은 10:30부터 가능합니다.'},
  {id:'notice_2',text:'예약한 입장시간에 맞춰 방문해주세요.'}
]};

let FS=null,AUTH=null,guide=clone(DEFAULT_GUIDE),draft=null,entryControl=null,ackEntry='',ackSig='',unsub=null;
function clone(v){return JSON.parse(JSON.stringify(v))}
function bridge(){return window.zrReservationFirebase||null}
function isStaff(){const z=bridge(),u=z?.auth?.currentUser;return !!u&&String(u.email||'').toLowerCase()===STAFF_EMAIL.toLowerCase()}
function normalize(raw){
  const s=raw&&typeof raw==='object'?raw:{};
  const contents=(Array.isArray(s.contents)?s.contents:DEFAULT_GUIDE.contents).slice(0,10).map((x,i)=>({
    id:String(x?.id||uid('guide')),name:String(x?.name||`컨텐츠 ${i+1}`).trim()||`컨텐츠 ${i+1}`,
    duration:String(x?.duration??'').replace(/[^0-9]/g,'').slice(0,3),imageUrl:safeUrl(x?.imageUrl),description:String(x?.description||''),enabled:x?.enabled!==false
  }));
  const notices=(Array.isArray(s.notices)?s.notices:DEFAULT_GUIDE.notices).slice(0,20).map(x=>({id:String(x?.id||uid('notice')),text:String(x?.text||'').trim()})).filter(x=>x.text);
  return {contents,notices};
}
function sig(g){return JSON.stringify([g.contents.map(x=>[x.id,x.name,x.duration,x.imageUrl,x.description,x.enabled]),g.notices.map(x=>[x.id,x.text])])}
function visible(el){return !!el&&getComputedStyle(el).display!=='none'&&getComputedStyle(el).visibility!=='hidden'&&el.getClientRects().length>0}
function customerVisible(){const v=$('customerView');return !!v&&!v.classList.contains('hidden')&&getComputedStyle(v).display!=='none'}

function injectStyle(){if($('zrGuideStyleV19'))return;const s=document.createElement('style');s.id='zrGuideStyleV19';s.textContent=`
.zr-guide-modal{position:fixed;inset:0;z-index:10060;background:rgba(16,25,20,.55);display:flex;align-items:center;justify-content:center;padding:14px;box-sizing:border-box}.zr-guide-modal.hidden{display:none!important}.zr-guide-sheet{width:min(760px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 24px 80px rgba(0,0,0,.26);padding:18px;box-sizing:border-box;-webkit-overflow-scrolling:touch}.zr-guide-head h2{margin:0;font-size:21px}.zr-guide-head p{margin:6px 0 0;color:#69736c;font-size:13px;line-height:1.55}.zr-guide-entry{display:inline-flex;margin-top:10px;padding:7px 10px;border-radius:999px;background:#e9f3ed;color:#2f6b4f;font-weight:800;font-size:12px}.zr-guide-cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:15px}.zr-guide-card{border:1px solid #dde4df;border-radius:14px;overflow:hidden;background:#fff}.zr-guide-img{width:100%;aspect-ratio:16/9;object-fit:cover;display:block;background:#f0f3f1}.zr-guide-card-body{padding:12px}.zr-guide-card h3{margin:0;font-size:16px}.zr-guide-duration{display:inline-block;margin-top:6px;padding:4px 7px;border-radius:7px;background:#f0f5f2;color:#436453;font-size:11px;font-weight:800}.zr-guide-desc{margin:8px 0 0;font-size:13px;line-height:1.6;color:#4f5b53;white-space:pre-line}.zr-guide-notices{margin-top:15px;padding:13px 14px;border-radius:13px;background:#fff8e9;border:1px solid #efdfb4}.zr-guide-notices h3{margin:0 0 8px;font-size:15px}.zr-guide-notices ul{margin:0;padding-left:20px}.zr-guide-notices li{margin:5px 0;font-size:13px;line-height:1.55}.zr-guide-actions{display:grid;grid-template-columns:1fr 1.7fr;gap:9px;position:sticky;bottom:-18px;background:#fff;padding:14px 0 2px;margin-top:14px}.zr-guide-actions button{min-height:48px;border-radius:11px;border:0;font-weight:900;font-size:14px;cursor:pointer}.zr-guide-back{background:#eef1ee;color:#526057}.zr-guide-confirm{background:#2f6b4f;color:#fff}
#zrGuideAdminSection .zrga-toolbar{display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:12px}.zrga-list{display:grid;gap:10px}.zrga-row{border:1px solid #dde4df;border-radius:14px;padding:12px;background:#fff}.zrga-head{display:flex;gap:8px;align-items:center;margin-bottom:9px}.zrga-head strong{flex:1}.zrga-mini{border:1px solid #d7ded9;background:#f5f7f5;border-radius:8px;padding:6px 8px;font-size:11px;font-weight:800;cursor:pointer}.zrga-del{color:#9b4545;background:#fff0f0;border-color:#ebcccc}.zrga-grid{display:grid;grid-template-columns:1.2fr .55fr;gap:8px}.zrga-grid .full{grid-column:1/-1}.zrga-grid label{display:block;font-size:11px;font-weight:800;color:#68736b;margin-bottom:4px}.zrga-grid input,.zrga-grid textarea{width:100%;box-sizing:border-box}.zrga-grid textarea{min-height:82px;resize:vertical}.zrga-preview{margin-top:8px;max-width:240px;border-radius:10px;overflow:hidden;border:1px solid #e0e5e1}.zrga-preview img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}.zrga-notice-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;margin-top:7px}.zrga-notice-row input{width:100%}.zrga-savebar{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.zrga-help{font-size:12px;color:#6d756f;line-height:1.55;margin:4px 0 12px}
@media(max-width:620px){.zr-guide-cards{grid-template-columns:1fr}.zr-guide-sheet{padding:15px}.zr-guide-actions{grid-template-columns:1fr}.zrga-grid{grid-template-columns:1fr}.zrga-grid .full{grid-column:auto}}
`;document.head.appendChild(s)}

function ensureModal(){if($('zrGuideModal'))return;const m=document.createElement('div');m.id='zrGuideModal';m.className='zr-guide-modal hidden';m.innerHTML=`<div class="zr-guide-sheet"><div class="zr-guide-head"><h2>방문 전 꼭 확인해주세요</h2><p>선택한 입장시간 기준으로 방문 컨텐츠와 주의사항을 확인해주세요.</p><div class="zr-guide-entry" id="zrGuideEntry"></div></div><div class="zr-guide-cards" id="zrGuideCards"></div><div id="zrGuideNotices"></div><div class="zr-guide-actions"><button type="button" class="zr-guide-back" id="zrGuideBack">입장시간 다시 선택</button><button type="button" class="zr-guide-confirm" id="zrGuideConfirm">안내사항을 확인했습니다</button></div></div>`;document.body.appendChild(m);$('zrGuideBack').onclick=()=>{m.classList.add('hidden');ackEntry='';ackSig='';setTimeout(()=>entryControl?.focus?.(),30)};$('zrGuideConfirm').onclick=()=>{const v=String(entryControl?.value||'').trim();if(!v)return;m.classList.add('hidden');ackEntry=v;ackSig=sig(guide);toast('방문 안내사항을 확인했습니다.')}}
function renderModal(control){entryControl=control||entryControl;const v=String(entryControl?.value||'').trim();if(!v)return;$('zrGuideEntry').textContent=`선택한 입장시간 ${v}`;const active=guide.contents.filter(x=>x.enabled);$('zrGuideCards').innerHTML=active.map(x=>{const u=safeUrl(x.imageUrl),d=Number(x.duration||0);return `<article class="zr-guide-card">${u?`<img class="zr-guide-img" src="${esc(u)}" alt="${esc(x.name)}" onerror="this.style.display='none'">`:''}<div class="zr-guide-card-body"><h3>${esc(x.name)}</h3>${d?`<span class="zr-guide-duration">평균 소요시간 약 ${d}분</span>`:''}${x.description?`<p class="zr-guide-desc">${esc(x.description)}</p>`:''}</div></article>`}).join('');$('zrGuideNotices').innerHTML=guide.notices.length?`<section class="zr-guide-notices"><h3>방문 전 주의사항</h3><ul>${guide.notices.map(x=>`<li>${esc(x.text)}</li>`).join('')}</ul></section>`:''}
function openGuide(c){ensureModal();renderModal(c);$('zrGuideModal').classList.remove('hidden');const sh=$('zrGuideModal').querySelector('.zr-guide-sheet');if(sh)sh.scrollTop=0}
function labelText(el){let out='';if(el.id){try{document.querySelectorAll(`label[for="${CSS.escape(el.id)}"]`).forEach(l=>out+=' '+l.textContent)}catch{}}const own=el.closest('label');if(own)out+=' '+own.textContent;let p=el.parentElement,n=0;while(p&&n++<3){const t=(p.textContent||'').replace(/\s+/g,' ').trim();if(t.length<100)out+=' '+t;p=p.parentElement}return out}
function looksTime(el){if(!el?.matches?.('select,input'))return false;if(el.matches('input[type="time"]'))return true;if(el.tagName==='SELECT')return [...el.options].slice(0,8).some(o=>/^\d{1,2}:\d{2}$/.test(String(o.value||o.textContent).trim()));return /^\d{1,2}:\d{2}$/.test(String(el.value||''))}
function isEntry(el){if(!looksTime(el)||el.closest('#adminView'))return false;const k=`${el.id||''} ${el.name||''} ${el.getAttribute('aria-label')||''} ${el.placeholder||''}`.toLowerCase();if(/entry|admission/.test(k))return true;const t=labelText(el).replace(/\s/g,'');return t.includes('입장시간')||(t.includes('입장')&&!t.includes('퇴장')&&t.length<80)}
function findEntry(){return [...document.querySelectorAll('select,input')].find(el=>isEntry(el)&&visible(el))||null}
function ackOk(c){const v=String(c?.value||'').trim();return !!v&&ackEntry===v&&ackSig===sig(guide)}
function bindCustomer(){document.addEventListener('change',e=>{const el=e.target;if(!customerVisible()||!isEntry(el))return;entryControl=el;ackEntry='';ackSig='';if(String(el.value||'').trim())setTimeout(()=>openGuide(el),20)},true);document.addEventListener('click',e=>{if(!customerVisible())return;const b=e.target?.closest?.('button,input[type="submit"],a');if(!b||b.closest('#zrGuideModal'))return;const t=(b.textContent||b.value||'').replace(/\s+/g,'');if(!/(예약.*(신청|완료|하기)|신청하기|예약하기)/.test(t)||/예약확인|추가예약/.test(t))return;const c=findEntry();if(c&&String(c.value||'').trim()&&!ackOk(c)){e.preventDefault();e.stopImmediatePropagation();openGuide(c);toast('방문 안내사항 확인이 필요합니다.')}},true);document.addEventListener('submit',e=>{if(!customerVisible())return;const c=[...(e.target?.querySelectorAll?.('select,input')||[])].find(isEntry)||findEntry();if(c&&String(c.value||'').trim()&&!ackOk(c)){e.preventDefault();e.stopImmediatePropagation();openGuide(c)}},true)}

function ensureAdmin(){if($('zrGuideAdminTab'))return true;const tabs=document.querySelector('#adminView .admin-tabs');if(!tabs)return false;const btn=document.createElement('button');btn.id='zrGuideAdminTab';btn.className='btn-gray';btn.textContent='고객 안내 관리';tabs.appendChild(btn);const sec=document.createElement('section');sec.id='zrGuideAdminSection';sec.className='hidden';sec.innerHTML=`<div class="card" style="margin-top:14px"><div class="zrga-toolbar"><div><h2 style="margin:0">고객 안내 관리</h2><div class="zrga-help">고객이 입장시간을 선택하면 표시되는 컨텐츠·사진·평균 소요시간·주의사항을 관리합니다.</div></div><button type="button" class="btn-soft" id="zrGuideAddContent">+ 컨텐츠 추가</button></div><div id="zrGuideAdminContents" class="zrga-list"></div><div style="margin-top:18px"><div class="zrga-toolbar"><h3 style="margin:0">방문 전 주의사항</h3><button type="button" class="btn-soft" id="zrGuideAddNotice">+ 주의사항 추가</button></div><div id="zrGuideAdminNotices"></div></div><div class="zrga-savebar"><button type="button" class="btn-primary" id="zrGuideAdminSave">안내 설정 저장</button></div></div>`;document.querySelector('#adminView').appendChild(sec);btn.onclick=openAdmin;document.addEventListener('click',e=>{const b=e.target.closest?.('#adminView .admin-tabs button');if(b&&b!==btn)sec.classList.add('hidden')});$('zrGuideAddContent').onclick=()=>{collect();if(draft.contents.length>=10)return toast('컨텐츠는 최대 10개까지 등록할 수 있습니다.');draft.contents.push({id:uid('guide'),name:'새 컨텐츠',duration:'',imageUrl:'',description:'',enabled:true});renderAdmin()};$('zrGuideAddNotice').onclick=()=>{collect();if(draft.notices.length>=20)return toast('주의사항은 최대 20개까지 등록할 수 있습니다.');draft.notices.push({id:uid('notice'),text:''});renderAdmin()};$('zrGuideAdminSave').onclick=saveAdmin;return true}
function openAdmin(){document.querySelectorAll('#adminView section[id^="tab-"]').forEach(s=>s.classList.add('hidden'));document.querySelectorAll('#adminView .admin-tabs button').forEach(b=>b.className='btn-gray');$('zrGuideAdminSection').classList.remove('hidden');$('zrGuideAdminTab').className='btn-primary';draft=clone(guide);renderAdmin()}
function collect(){if(!draft)draft=clone(guide);document.querySelectorAll('#zrGuideAdminContents .zrga-row[data-i]').forEach(r=>{const x=draft.contents[Number(r.dataset.i)];if(!x)return;x.name=r.querySelector('[data-k="name"]')?.value.trim()||x.name;x.duration=String(r.querySelector('[data-k="duration"]')?.value||'').replace(/[^0-9]/g,'').slice(0,3);x.imageUrl=safeUrl(r.querySelector('[data-k="imageUrl"]')?.value||'');x.description=String(r.querySelector('[data-k="description"]')?.value||'');x.enabled=!!r.querySelector('[data-k="enabled"]')?.checked});document.querySelectorAll('#zrGuideAdminNotices .zrga-notice-row[data-i]').forEach(r=>{const x=draft.notices[Number(r.dataset.i)];if(x)x.text=r.querySelector('input')?.value||''})}
function move(a,i,d){const j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]]}
function renderAdmin(){if(!draft)return;const root=$('zrGuideAdminContents');root.innerHTML=draft.contents.map((x,i)=>{const u=safeUrl(x.imageUrl);return `<div class="zrga-row" data-i="${i}"><div class="zrga-head"><strong>컨텐츠 ${i+1}</strong><button class="zrga-mini" data-up="${i}">↑</button><button class="zrga-mini" data-down="${i}">↓</button><button class="zrga-mini zrga-del" data-del="${i}">삭제</button></div><div class="zrga-grid"><div><label>컨텐츠명</label><input data-k="name" value="${esc(x.name)}"></div><div><label>평균 소요시간(분)</label><input data-k="duration" type="number" min="0" max="999" value="${esc(x.duration)}" placeholder="예: 45"></div><div class="full"><label>사진 URL</label><input data-k="imageUrl" value="${esc(x.imageUrl)}" placeholder="https://..."></div>${u?`<div class="full zrga-preview"><img src="${esc(u)}" alt="미리보기" onerror="this.parentElement.style.display='none'"></div>`:''}<div class="full"><label>간단 설명</label><textarea data-k="description">${esc(x.description)}</textarea></div><div class="full"><label style="display:flex;gap:7px;align-items:center"><input data-k="enabled" type="checkbox" ${x.enabled?'checked':''} style="width:auto"> 고객에게 노출</label></div></div></div>`}).join('');root.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{collect();move(draft.contents,Number(b.dataset.up),-1);renderAdmin()});root.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{collect();move(draft.contents,Number(b.dataset.down),1);renderAdmin()});root.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{collect();draft.contents.splice(Number(b.dataset.del),1);renderAdmin()});const n=$('zrGuideAdminNotices');n.innerHTML=draft.notices.map((x,i)=>`<div class="zrga-notice-row" data-i="${i}"><input value="${esc(x.text)}" placeholder="주의사항을 입력해주세요."><button class="zrga-mini zrga-del" data-ndel="${i}">삭제</button></div>`).join('');n.querySelectorAll('[data-ndel]').forEach(b=>b.onclick=()=>{collect();draft.notices.splice(Number(b.dataset.ndel),1);renderAdmin()})}
async function saveAdmin(){collect();const z=bridge();if(!FS||!z?.db||!isStaff())return toast('관리자 DB 로그인을 확인해주세요.');const b=$('zrGuideAdminSave'),old=b.textContent;b.disabled=true;b.textContent='저장 중...';try{const cleaned=normalize(draft);await FS.setDoc(FS.doc(z.db,COLLECTION,DOC_ID),{contents:cleaned.contents,notices:cleaned.notices,updatedAt:FS.serverTimestamp()},{merge:true});guide=cleaned;draft=clone(cleaned);toast('고객 안내 설정을 저장했습니다.')}catch(e){const c=String(e?.code||e?.name||'unknown').replace(/^firestore\//,'');console.error('guide v19 save',e);toast(`고객 안내 저장 실패 · ${c}`);try{alert(`고객 안내 설정 저장 실패\n오류코드: ${c}`)}catch{}}finally{b.disabled=false;b.textContent=old}}

async function initFirebase(){try{const [fs,au]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FV}/firebase-firestore.js`),import(`https://www.gstatic.com/firebasejs/${FV}/firebase-auth.js`)]);FS=fs;AUTH=au;const t=setInterval(()=>{const z=bridge();if(!z?.db||!z?.auth)return;clearInterval(t);AUTH.onAuthStateChanged(z.auth,()=>setTimeout(subscribe,20));subscribe()},200);setTimeout(()=>clearInterval(t),15000)}catch(e){console.error('guide v19 firebase',e)}}
function subscribe(){const z=bridge();if(!FS||!z?.db||!z?.auth?.currentUser)return;if(unsub){unsub();unsub=null}try{unsub=FS.onSnapshot(FS.doc(z.db,COLLECTION,DOC_ID),s=>{guide=normalize(s.exists()?s.data():DEFAULT_GUIDE);ackEntry='';ackSig='';if($('zrGuideAdminSection')&&!$('zrGuideAdminSection').classList.contains('hidden')){draft=clone(guide);renderAdmin()}},e=>console.debug('guide v19 read',e))}catch(e){console.debug('guide v19 subscribe',e)}}
function boot(){injectStyle();ensureModal();bindCustomer();const t=setInterval(()=>{if(ensureAdmin())clearInterval(t)},250);setTimeout(()=>clearInterval(t),15000);initFirebase()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();