(()=>{
'use strict';
const $=id=>document.getElementById(id),START=600,MAX=1080,SLOT=15;
const LABEL={f4:'4F 베이직',f5:'5F 워터가든',meal:'식사',play:'놀이터'},CLS={f4:'zrsc-f4',f5:'zrsc-f5',meal:'zrsc-meal',play:'zrsc-play'};
const pad=n=>String(n).padStart(2,'0'),tm=m=>pad(Math.floor(m/60))+':'+pad(m%60),mn=t=>{if(!t)return null;const [h,m]=String(t).split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),tel=s=>String(s||'').replace(/\D/g,'');
function read(){try{return JSON.parse(localStorage.getItem('zr_bookings')||'[]')}catch{return[]}}
function style(){if($('zrCustomerScheduleStyle'))return;const s=document.createElement('style');s.id='zrCustomerScheduleStyle';s.textContent=`.zr-customer-schedule{margin-top:12px;border:1px solid #cfe3d6;background:#f8fcf9;border-radius:14px;padding:13px}.zr-customer-schedule h3{margin:0 0 5px;font-size:15px}.zr-customer-schedule .help{margin-bottom:6px}.zr-customer-line{position:relative;height:50px;margin-top:9px;border:1px solid #dfe5df;border-radius:10px;background:#fff;overflow:hidden}.zr-customer-grid{position:absolute;inset:0;background-image:linear-gradient(to right,rgba(47,107,79,.10) 1px,transparent 1px)}.zr-customer-seg{position:absolute;top:4px;bottom:4px;border-radius:7px;padding:4px 6px;box-sizing:border-box;overflow:hidden;font-size:10px;z-index:2}.zr-customer-seg b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.zr-customer-seg small{font-size:9px;white-space:nowrap}.zrsc-f4{background:#f8d7bf}.zrsc-f5{background:#cfe7f7}.zrsc-meal{background:#fff0a8}.zrsc-play{background:#d8efc9}.zr-customer-legend{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.zr-customer-legend span{font-size:10px;padding:4px 6px;border-radius:7px}`;document.head.appendChild(s)}
function axis(b,segs){let end=mn(b.exitTime)||900;for(const s of segs){const z=mn(s.end);if(z!=null)end=Math.max(end,z)}end=Math.max(900,Math.ceil(end/60)*60);return {start:START,end:Math.min(MAX,end)}}
function pct(t,a){const m=mn(t);return m==null?0:Math.max(0,Math.min(100,(m-a.start)/(a.end-a.start)*100))}
function segHtml(s,a){if(!s?.start||!s?.end)return'';const w=Math.max(1,pct(s.end,a)-pct(s.start,a));return `<div class="zr-customer-seg ${CLS[s.type]||''}" style="left:${pct(s.start,a)}%;width:${w}%"><b>${LABEL[s.type]||s.type}</b>${w>=9?`<small>${s.start}~${s.end}</small>`:''}</div>`}
function render(){const list=$('existingBookingList');if(!list)return;let box=$('zrCustomerScheduleBox');if(!box){box=document.createElement('div');box.id='zrCustomerScheduleBox';list.insertAdjacentElement('afterend',box)}const manager=$('startManager')?.value.trim()||'',contact=tel($('startContact')?.value||'');if(!manager||!contact){box.innerHTML='';return}const found=read().filter(b=>b&&!b.__availabilityOnly&&b.status==='confirmed'&&b.schedulePublished&&b.customerSchedule&&String(b.managerName||'').trim()===manager&&tel(b.contact)===contact);box.innerHTML=found.map(b=>{const cs=b.customerSchedule||{},segs=Array.isArray(cs.segments)?[...cs.segments].sort((a,z)=>String(a.start).localeCompare(String(z.start))):[],a=axis(b,segs),grid=`${SLOT/(a.end-a.start)*100}% 100%`;return `<div class="zr-customer-schedule"><h3>${esc(b.orgName||cs.org||'예약')} · 확정 스케줄</h3><div class="help">관리자가 확정한 방문 스케줄입니다. 예약 ${esc(b.entryTime||cs.entryTime||'')}~${esc(b.exitTime||cs.exitTime||'')}</div><div class="zr-customer-line"><div class="zr-customer-grid" style="background-size:${grid}"></div>${segs.map(s=>segHtml(s,a)).join('')}</div><div class="zr-customer-legend"><span class="zrsc-f4">4F 베이직</span><span class="zrsc-f5">5F 워터가든</span><span class="zrsc-meal">식사</span><span class="zrsc-play">놀이터</span></div></div>`}).join('')}
function hook(){style();['lookupBooking','checkExisting'].forEach(id=>{const e=$(id);if(e&&!e.dataset.zrCustomerSchedule){e.dataset.zrCustomerSchedule='1';e.addEventListener('click',()=>setTimeout(render,250))}});const list=$('existingBookingList');if(list&&!list.dataset.zrCustomerSchedule){list.dataset.zrCustomerSchedule='1';new MutationObserver(()=>setTimeout(render,0)).observe(list,{childList:true,subtree:true})}}
function boot(){const t=setInterval(()=>{hook();if($('lookupBooking')&&$('existingBookingList'))clearInterval(t)},300);setTimeout(()=>clearInterval(t),15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();