(()=>{
'use strict';
if(window.__ZR_PARKING_INFO_V29)return;
window.__ZR_PARKING_INFO_V29=true;
const FV='12.17.1',STAFF_EMAIL='zoolung09@zoolungzoolung.com',COLLECTION='customerGuides',DOC_ID='main';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=v=>JSON.parse(JSON.stringify(v)),toast=s=>{try{window.toast?.(s)}catch{}};
const SPRITE='./assets/parking_sprite.jpg?v=29';
const DEF={title:'주차 및 인솔 안내',dropoffTitle:'승·하차 장소',dropoffPlace:'아이스토어 라크몽점 앞 또는 황금동상 앞',dropoffAddress:'경기 화성시 동탄구 송동 741',dropoffNote:'하차지점에서 인솔자 대기 예정\n도움 필요 시 도착 5분 전 연락해주세요.\n건물 지하 차량 높이 제한 2.1m',busTitle:'버스 주차 장소',busPlace:'동탄 제2차고지 앞',busAddress:'경기도 화성시 장지동 1054',busNote:'25인승·45인승 버스 주차 가능\n주변 주정차 단속구간을 피해 주차해주세요.',dropoffImage:'',busOkImage:'',busNo1Image:'',busNo2Image:''};
let FS=null,db=null,unsub=null,current=clone(DEF),submitBypass=false,pendingButton=null;
const safe=u=>/^(https?:\/\/|\.\/|\/)/i.test(String(u||'').trim())?String(u).trim():'';
const norm=r=>{const s=r&&typeof r==='object'?r:{},t=(k,m=800)=>String(s[k]??DEF[k]).slice(0,m);return{title:t('title',80),dropoffTitle:t('dropoffTitle',80),dropoffPlace:t('dropoffPlace',160),dropoffAddress:t('dropoffAddress',160),dropoffNote:t('dropoffNote'),busTitle:t('busTitle',80),busPlace:t('busPlace',160),busAddress:t('busAddress',160),busNote:t('busNote'),dropoffImage:safe(s.dropoffImage),busOkImage:safe(s.busOkImage),busNo1Image:safe(s.busNo1Image),busNo2Image:safe(s.busNo2Image)}};
const lines=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
const staff=()=>{const u=window.zrReservationFirebase?.auth?.currentUser;return !!u&&String(u.email||'').toLowerCase()===STAFF_EMAIL};
const customerVisible=()=>{const v=$('customerView');return !!v&&!v.classList.contains('hidden')&&getComputedStyle(v).display!=='none'};
function style(){
 if($('zrParkingStyleV29'))return;const s=document.createElement('style');s.id='zrParkingStyleV29';s.textContent=`
 .zrpk{margin-top:14px;border:1px solid #dce5df;background:#fff;border-radius:16px;padding:15px}.zrpk h3{margin:0;font-size:17px}.zrpk-head{display:flex;gap:8px;align-items:center;margin-bottom:12px}.zrpk-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.zrpk-box{border:1px solid #e4e9e5;border-radius:13px;padding:12px;background:#fbfcfb}.zrpk-box h4{margin:0 0 7px;font-size:15px}.zrpk-place{font-weight:850;line-height:1.5}.zrpk-addr{margin-top:6px;padding:8px 9px;background:#f1f5f2;border-radius:9px;font-size:12px;line-height:1.5}.zrpk-notes{margin:9px 0 0;padding-left:18px;color:#536159}.zrpk-notes li{margin:4px 0;font-size:12px;line-height:1.5}.zrpk-photos{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.zrpk-photo{position:relative;aspect-ratio:2/1;border-radius:9px;overflow:hidden;background-image:url("${SPRITE}");background-size:200% 200%;background-repeat:no-repeat}.zrpk-photo.p1{background-position:0 0}.zrpk-photo.p2{background-position:100% 0}.zrpk-photo.p3{background-position:0 100%}.zrpk-photo.p4{background-position:100% 100%}.zrpk-photo img{width:100%;height:100%;object-fit:cover;display:block}.zrpk-photo span{position:absolute;right:5px;bottom:4px;background:rgba(255,255,255,.9);border-radius:99px;padding:2px 5px;font-size:10px;font-weight:900}#zrParkingAdminSection{margin-top:18px;padding:14px;border:1px solid #d9e3dc;border-radius:14px;background:#f8fbf9}.zrpk-admin{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px}.zrpk-admin .full{grid-column:1/-1}.zrpk-admin label{display:block;font-size:11px;font-weight:850;color:#68736b;margin-bottom:4px}.zrpk-admin input,.zrpk-admin textarea{width:100%;box-sizing:border-box}.zrpk-admin textarea{min-height:78px;resize:vertical}.zrpk-save{display:flex;justify-content:flex-end;margin-top:12px}.zrfinal{position:fixed;inset:0;z-index:10120;background:rgba(16,25,20,.56);display:flex;align-items:center;justify-content:center;padding:14px}.zrfinal.hidden{display:none!important}.zrfinal-sheet{width:min(620px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:18px;padding:18px;box-sizing:border-box}.zrfinal-sheet h2{margin:0;font-size:20px}.zrfinal-check{padding:10px 11px;border-radius:10px;background:#f1f6f3;font-size:13px;font-weight:800;margin-top:7px}.zrfinal-parking{border:1px solid #e0e6e2;border-radius:12px;padding:12px;margin-top:12px}.zrfinal-parking h3{margin:0 0 8px}.zrfinal-parking p{margin:5px 0;font-size:13px;line-height:1.55}.zrfinal-actions{display:grid;grid-template-columns:1fr 1.7fr;gap:9px;margin-top:14px}.zrfinal-actions button{min-height:48px;border:0;border-radius:11px;font-weight:900}.zrfinal-back{background:#eef1ee;color:#526057}.zrfinal-ok{background:#2f6b4f;color:white}@media(max-width:650px){.zrpk-grid,.zrpk-admin{grid-template-columns:1fr}.zrpk-admin .full{grid-column:auto}.zrfinal-actions{grid-template-columns:1fr}}`;
 document.head.appendChild(s);
}
function photo(cls,url,label){const u=safe(url);return `<div class="zrpk-photo ${cls}">${u?`<img src="${esc(u)}" alt="">`:''}<span>${label}</span></div>`}
function html(){
 const p=current,n=s=>lines(s).map(x=>`<li>${esc(x)}</li>`).join('');
 return `<div class="zrpk-head"><b style="font-size:21px">🚗</b><h3>${esc(p.title)}</h3></div><div class="zrpk-grid"><section class="zrpk-box"><h4>${esc(p.dropoffTitle)}</h4><div class="zrpk-place">${esc(p.dropoffPlace)}</div><div class="zrpk-addr">📍 네이버지도 주소: <b>${esc(p.dropoffAddress)}</b></div><div class="zrpk-photos">${photo('p1',p.dropoffImage,'승·하차')}</div>${n(p.dropoffNote)?`<ul class="zrpk-notes">${n(p.dropoffNote)}</ul>`:''}</section><section class="zrpk-box"><h4>🚌 ${esc(p.busTitle)}</h4><div class="zrpk-place">${esc(p.busPlace)}</div><div class="zrpk-addr">📍 네이버지도 주소: <b>${esc(p.busAddress)}</b></div><div class="zrpk-photos">${photo('p2',p.busOkImage,'주차 가능 ✅')}${photo('p3',p.busNo1Image,'주차 금지 ❌')}${photo('p4',p.busNo2Image,'주차 금지 ❌')}</div>${n(p.busNote)?`<ul class="zrpk-notes">${n(p.busNote)}</ul>`:''}</section></div>`;
}
function anchor(){const a=$('entryTime'),b=$('exitTime');if(!a||!b)return null;const c=[b.closest('.grid2'),b.closest('.grid'),b.parentElement?.parentElement,b.parentElement].filter(Boolean);return c.find(x=>x.contains(a)&&x.contains(b))||b.parentElement}
function renderCard(){let r=$('zrParkingInfoCard');if(!r){const a=anchor();if(!a)return false;r=document.createElement('section');r.id='zrParkingInfoCard';r.className='zrpk';a.insertAdjacentElement('afterend',r)}r.innerHTML=html();return true}
const fld=(l,k,v,full=false,area=false)=>`<div class="${full?'full':''}"><label>${l}</label>${area?`<textarea data-pk="${k}">${esc(v)}</textarea>`:`<input data-pk="${k}" value="${esc(v)}">`}</div>`;
function renderAdmin(){
 const sec=$('zrGuideAdminSection');if(!sec)return false;let r=$('zrParkingAdminSection');if(!r){r=document.createElement('section');r.id='zrParkingAdminSection';const sb=sec.querySelector('.zrga-savebar');sb?sb.insertAdjacentElement('beforebegin',r):sec.appendChild(r)}const p=current;
 r.innerHTML=`<h3>🚗 주차 안내 관리</h3><div class="zrga-help">예약 화면의 주차·인솔 안내 문구를 수정합니다. 사진 URL을 비워두면 기본 사진 4장이 표시됩니다.</div><div class="zrpk-admin">${fld('안내 제목','title',p.title,true)}${fld('승·하차 제목','dropoffTitle',p.dropoffTitle)}${fld('승·하차 장소','dropoffPlace',p.dropoffPlace)}${fld('승·하차 네이버지도 주소','dropoffAddress',p.dropoffAddress,true)}${fld('승·하차 안내 문구','dropoffNote',p.dropoffNote,true,true)}${fld('승·하차 사진 URL (선택)','dropoffImage',p.dropoffImage,true)}${fld('버스 주차 제목','busTitle',p.busTitle)}${fld('버스 주차 장소','busPlace',p.busPlace)}${fld('버스 주차 네이버지도 주소','busAddress',p.busAddress,true)}${fld('버스 주차 안내 문구','busNote',p.busNote,true,true)}${fld('주차 가능 사진 URL (선택)','busOkImage',p.busOkImage,true)}${fld('주차 금지 사진 URL 1 (선택)','busNo1Image',p.busNo1Image,true)}${fld('주차 금지 사진 URL 2 (선택)','busNo2Image',p.busNo2Image,true)}</div><div class="zrpk-save"><button type="button" class="btn-primary" id="zrParkingSave">주차 안내 저장</button></div>`;
 $('zrParkingSave').onclick=save;
 return true;
}
async function save(){
 if(!staff())return toast('관리자 DB 로그인을 확인해주세요.');if(!FS||!db)return toast('주차 안내 DB 연결 중입니다.');
 const b=$('zrParkingSave'),old=b?.textContent||'';if(b){b.disabled=true;b.textContent='저장 중...'}
 try{const o=clone(current);document.querySelectorAll('#zrParkingAdminSection [data-pk]').forEach(x=>o[x.dataset.pk]=x.value);const cleaned=norm(o);await FS.setDoc(FS.doc(db,COLLECTION,DOC_ID),{parking:cleaned,updatedAtMs:Date.now()},{merge:true});current=cleaned;renderCard();renderAdmin();toast('주차 안내를 저장했습니다.')}catch(e){console.error(e);toast('주차 안내 저장에 실패했습니다.')}finally{if(b){b.disabled=false;b.textContent=old}}
}
function finalModal(){if($('zrFinalGuideModal'))return;const m=document.createElement('div');m.id='zrFinalGuideModal';m.className='zrfinal hidden';m.innerHTML=`<div class="zrfinal-sheet"><h2>예약 전 최종 확인</h2><div id="zrFinalChecks"></div><div class="zrfinal-parking" id="zrFinalParking"></div><div class="zrfinal-actions"><button type="button" class="zrfinal-back" id="zrFinalBack">예약 내용 다시 보기</button><button type="button" class="zrfinal-ok" id="zrFinalOk">확인 후 예약 신청</button></div></div>`;document.body.appendChild(m);$('zrFinalBack').onclick=()=>m.classList.add('hidden');$('zrFinalOk').onclick=()=>{m.classList.add('hidden');submitBypass=true;const b=pendingButton;pendingButton=null;setTimeout(()=>{b?.click?.();setTimeout(()=>submitBypass=false,150)},0)}}
function showFinal(){finalModal();const play=String($('playUse')?.value||'')==='yes';$('zrFinalChecks').innerHTML=`<div class="zrfinal-check">✅ 동물원 이용 안내 확인 완료</div>${play?'<div class="zrfinal-check">✅ 놀이터 이용 안내 확인 완료</div>':'<div class="zrfinal-check">➖ 놀이터 이용 안 함</div>'}`;$('zrFinalParking').innerHTML=`<h3>🚗 ${esc(current.title)}</h3><p><b>${esc(current.dropoffTitle)}</b><br>${esc(current.dropoffPlace)}<br>📍 ${esc(current.dropoffAddress)}</p><p><b>${esc(current.busTitle)}</b><br>${esc(current.busPlace)}<br>📍 ${esc(current.busAddress)}</p>`;$('zrFinalGuideModal').classList.remove('hidden')}
const booking=b=>{const t=(b?.textContent||b?.value||'').replace(/\s+/g,'');return !!b&&/(예약.*(신청|완료|하기)|신청하기|예약하기)/.test(t)&&!/예약확인|추가예약/.test(t)};
function bindFinal(){document.addEventListener('click',e=>{if(submitBypass||!customerVisible())return;const b=e.target?.closest?.('button,input[type="submit"],a');if(!booking(b)||b.closest('#zrFinalGuideModal')||b.closest('#zrGuideModal')||b.closest('#zrPlayGuideModal'))return;e.preventDefault();e.stopImmediatePropagation();pendingButton=b;showFinal()},true)}
async function init(){try{FS=await import(`https://www.gstatic.com/firebasejs/${FV}/firebase-firestore.js`);const z=window.zrReservationFirebase;if(!z?.db)throw 0;db=z.db;if(unsub)unsub();unsub=FS.onSnapshot(FS.doc(db,COLLECTION,DOC_ID),s=>{current=norm(s.exists()?s.data()?.parking:null);renderCard();if($('zrGuideAdminSection')&&!$('zrGuideAdminSection').classList.contains('hidden'))renderAdmin()},e=>console.error('parking read',e))}catch(e){console.error('parking init',e)}}
function boot(){style();const a=setInterval(()=>{if(renderCard())clearInterval(a)},200);setTimeout(()=>clearInterval(a),20000);const b=setInterval(()=>{const t=$('zrGuideAdminTab');if(!t)return;t.addEventListener('click',()=>setTimeout(renderAdmin,80));clearInterval(b)},250);setTimeout(()=>clearInterval(b),20000);bindFinal();const w=setInterval(()=>{if(!window.zrReservationFirebase?.auth||!window.zrReservationFirebase?.db)return;clearInterval(w);init()},200);setTimeout(()=>clearInterval(w),20000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();