import {state,$,START_MIN,MAX_PICK,SLOT,tm,min,clone,T,savePatch,writeError,toast} from './core.js';
import {contentPreview,scheduleEnhance} from './display.js';
let render=()=>{};
export function initContent(ctx){render=ctx.render;$("contentSave").onclick=save;$("contentCancel").onclick=$("contentClose").onclick=close;$("contentModal").onclick=e=>{if(e.target===$("contentModal"))close()}}
function opts(v){let h="";for(let m=START_MIN;m<=MAX_PICK;m+=SLOT){const t=tm(m);h+=`<option value="${t}" ${t===v?"selected":""}>${t}</option>`}return h}
function axis(){const used=[900];[...state.contentState.original,...state.contentState.changed].forEach(s=>{used.push(min(s.start),min(s.end))});const end=Math.max(900,Math.ceil(Math.max(...used.filter(x=>x!=null))/60)*60);return {start:START_MIN,end:Math.min(MAX_PICK,end)}}
function updatePreview(){const a=axis();contentPreview("originalRuler","originalTimeline",state.contentState.original,a);contentPreview("changedRuler","changedTimeline",state.contentState.changed,a)}
function rows(){$("contentRows").innerHTML=state.contentState.changed.map((s,i)=>{const tt=T[s.type]||T.free;return `<div class="contentRow" data-i="${i}"><div class="contentName ${tt[1]}">${tt[0]}</div><div><label>시작</label><select data-k="start">${opts(s.start)}</select></div><div><label>종료</label><select data-k="end">${opts(s.end)}</select></div></div>`}).join("");document.querySelectorAll(".contentRow").forEach(r=>r.querySelectorAll("select").forEach(sel=>sel.onchange=()=>{state.contentState.changed[Number(r.dataset.i)][sel.dataset.k]=sel.value;updatePreview()}));scheduleEnhance()}
export function openContentEditor(gid){const g=state.data.groups.find(z=>z.id===gid);if(!g)return;state.activeContentGid=String(gid);state.contentState={gid,original:clone(g.segments||[]),changed:clone(g.segments||[])};$("contentTitle").textContent=g.org+" · 컨텐츠 스케줄";rows();updatePreview();$("contentModal").classList.remove("hidden");scheduleEnhance()}
function validate(){const arr=state.contentState.changed.map(s=>({...s,a:min(s.start),b:min(s.end)}));for(const s of arr)if(s.b<=s.a)return "종료시간은 시작시간보다 늦어야 합니다.";const sorted=[...arr].sort((a,b)=>a.a-b.a);for(let i=1;i<sorted.length;i++)if(sorted[i].a<sorted[i-1].b)return "같은 단체의 컨텐츠 시간이 겹쳐요.";return ""}
async function save(){const err=validate();if(err)return toast(err);const g=state.data.groups.find(z=>z.id===state.contentState.gid);if(!g)return;const changed=clone(state.contentState.changed),old=clone(g.segments);g.segments=changed;render();try{await savePatch(g.id,{segments:changed});close();toast("컨텐츠 시간을 저장했습니다.")}catch(e){g.segments=old;render();writeError(e)}}
function close(){$("contentModal").classList.add("hidden");state.contentState=null;state.activeContentGid=""}
