import {state,$,T,DEFAULT_CATALOG,SHORT,SLOT,START_MIN,MAX_PICK,pad,tm,min,esc,currentList,today,tel} from './core.js';
let pending=false;
function fullAxisFor(groups){const used=[900];groups.forEach(g=>{[g.ps,g.pe,g.eta,g.aend].forEach(t=>{const m=min(t);if(m!=null)used.push(m)});(g.segments||[]).forEach(s=>{const a=min(s.start),b=min(s.end);if(a!=null)used.push(a);if(b!=null)used.push(b)})});let end=Math.max(900,Math.ceil(Math.max(...used)/60)*60);end=Math.min(MAX_PICK,end);return {start:START_MIN,end}}
function todayAxisFor(groups){
  const n=new Date(),nowm=n.getHours()*60+n.getMinutes();
  if(nowm<START_MIN)return fullAxisFor(groups);
  if(nowm>=MAX_PICK)return {start:Math.max(START_MIN,MAX_PICK-90),end:MAX_PICK};
  const starts=[],ends=[],recentCutoff=nowm-60;
  groups.forEach(g=>(g.segments||[]).forEach(s=>{
    const a=min(s.start),b=min(s.end);
    if(a==null||b==null||b<=a||b<recentCutoff||a>=MAX_PICK||b<=START_MIN)return;
    starts.push(Math.max(START_MIN,a));ends.push(Math.min(MAX_PICK,b));
  }));
  const floor30=m=>Math.floor(m/30)*30,ceil30=m=>Math.ceil(m/30)*30;
  let start=Math.max(START_MIN,floor30(Math.min(nowm-30,starts.length?Math.min(...starts):nowm-30)));
  let end=Math.min(MAX_PICK,ceil30(Math.max(nowm+30,ends.length?Math.max(...ends):nowm+30)));
  if(end-start<60){start=Math.max(START_MIN,end-60);if(end-start<60)end=Math.min(MAX_PICK,start+60)}
  return {start,end};
}
function axisFor(groups){return state.date===today()?todayAxisFor(groups):fullAxisFor(groups)}
function pct(t,a){const m=min(t);if(m==null)return 0;return Math.max(0,Math.min(100,(m-a.start)/(a.end-a.start)*100))}
export function rulerHtml(a){const span=a.end-a.start,step=span>360?60:30;let h='<div class="grid" style="background-size:'+((SLOT/span)*100)+'% 100%"></div>';for(let m=a.start;m<=a.end;m+=step){const p=(m-a.start)/span*100,cl=m===a.start?" first":m===a.end?" end":"";h+=`<span class="tick${cl}" style="left:${p}%">${tm(m)}</span>`}return h}
function segHtml(s,a,attrs=""){const sm=min(s.start),em=min(s.end);if(sm==null||em==null||em<=a.start||sm>=a.end)return "";const tt=T[s.type]||T.free,w=Math.max(1,pct(s.end,a)-pct(s.start,a));return `<div class="seg ${tt[1]}" ${attrs} style="left:${pct(s.start,a)}%;width:${w}%"><b>${tt[0]}</b><small>${s.start}~${s.end}</small></div>`}
function cat(type){return state.catalog.get(type)||DEFAULT_CATALOG[type]||DEFAULT_CATALOG.free}
function label(s){return s?.label||cat(s?.type).name||String(s?.type||"컨텐츠")}
function color(s){return s?.color||cat(s?.type).color||DEFAULT_CATALOG.free.color}
function short(s,l){return SHORT[s?.type]||(l||"").slice(0,2)||"기타"}
export function renderView(){
  $("date").value=state.date;const a=currentList(),axis=axisFor(a),n=new Date();$("ruler").innerHTML=rulerHtml(axis);$("rangeTxt").textContent=tm(axis.start)+"~"+tm(axis.end);
  const active=a.filter(g=>!g.cancelled),cancelled=a.filter(g=>g.cancelled);$("teams").textContent=active.length+"팀";$("cancelledCount").textContent=cancelled.length+"팀";
  $("reserved").textContent=active.reduce((s,g)=>s+Number(g.res||0),0)+"명";$("actualPaidSum").textContent=active.reduce((s,g)=>s+(g.actualPaid===""?0:Number(g.actualPaid||0)),0)+"명";$("actualChapSum").textContent=active.reduce((s,g)=>s+(g.actualChap===""?0:Number(g.actualChap||0)),0)+"명";
  $("nowtxt").textContent="현재 "+pad(n.getHours())+":"+pad(n.getMinutes());document.body.classList.toggle("viewLocked",!state.editMode);$("toolbar").classList.toggle("editing",state.editMode);$("editLock").className="editLock "+(state.editMode?"unlocked":"locked");$("editLock").textContent=state.editMode?"🔓 수정 가능":"🔒 수정 불가";
  if(!a.length){$("list").innerHTML='<div class="empty">등록된 단체 스케줄이 없습니다.</div>';scheduleEnhance();return}
  const nowm=n.getHours()*60+n.getMinutes(),np=state.date===today()&&nowm>=axis.start&&nowm<=axis.end?(nowm-axis.start)/(axis.end-axis.start)*100:null;
  $("list").innerHTML=a.map(g=>{const ss=(g.segments||[]).map(s=>segHtml(s,axis,`data-seg="${s.id}" data-g="${g.id}"`)).join(""),cafe=String(g.meal||"").includes("카페"),mealClass=cafe?"tag mealTag cafe":"tag mealTag";return `<article class="card ${state.editMode?"editable":""} ${g.cancelled?"cancelled":""}"><div class="head"><div class="org">${esc(g.org)}</div><span class="tag">${g.res}(${g.tea})명</span><span class="${mealClass}" ${cafe?`data-cafe="${g.id}"`:""}>${esc(g.meal||"")}</span>${!String(g.meal||"").includes("식사없음")?`<span class="tag locTag ${g.mealLoc?"hasLoc":"noLoc"}" data-loc="${g.id}" title="식사위치">📍 ${esc(g.mealLoc||"식사위치")}</span>`:""}<span class="tag appearanceTag ${g.appearance?"hasAppearance":"noAppearance"}" data-a="${g.id}" title="아이들 인상착의">👕 ${esc(g.appearance||"인상착의")}</span>${g.cancelled?'<span class="tag cancelTag">당일취소</span>':""}<button class="soft detail" data-e="${g.id}">상세</button></div><div class="meta"><span class="planT" data-q="plan" data-id="${g.id}">예약 ${g.ps}~${g.pe}</span><button type="button" class="live zr-quick-time ${g.eta?"has":""}" data-q="eta" data-id="${g.id}" aria-label="도착예정 시간 수정">도착예정 ${g.eta||"--:--"}</button><button type="button" class="live zr-quick-time ${g.aend?"has":""}" data-q="aend" data-id="${g.id}" aria-label="퇴장예정 시간 수정">퇴장예정 ${g.aend||"--:--"}</button><span class="live ${g.actualPaid!==""?"has":""}" data-q="actualPaid" data-id="${g.id}">유료 ${g.actualPaid!==""?g.actualPaid+"명":"--"}</span><span class="live ${g.actualChap!==""?"has":""}" data-q="actualChap" data-id="${g.id}">인솔 ${g.actualChap!==""?g.actualChap+"명":"--"}</span><div class="quick"><button class="check ${g.pay?"on":""}" data-c="pay" data-id="${g.id}">${g.pay?"✓ ":""}결제</button><button class="check ${g.book?"on":""}" data-c="book" data-id="${g.id}">${g.book?"✓ ":""}컬러북</button></div></div><div class="timeline"><div class="grid" style="background-size:${(SLOT/(axis.end-axis.start))*100}% 100%"></div>${ss}${np==null?"":`<div class="now" style="left:${np}%"></div>`}</div><div class="memo" data-m="${g.id}"><b>메모</b>${esc(g.memo||"메모 없음 · 눌러서 입력")}</div></article>`}).join("");scheduleEnhance();
}
export function contentPreview(rulerId,timelineId,segs,a){$(rulerId).innerHTML=rulerHtml(a);$(timelineId).innerHTML='<div class="grid" style="background-size:'+((SLOT/(a.end-a.start))*100)+'% 100%"></div>'+segs.map(s=>segHtml(s,a)).join("");scheduleEnhance()}
export function scheduleEnhance(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;enhanceDisplay()})}
function enhanceDisplay(){
  const byGroup=new Map(state.data.groups.map(g=>[String(g.id),g]));document.querySelectorAll('#list .card').forEach(card=>{const gid=card.querySelector('.detail[data-e]')?.dataset.e||card.querySelector('[data-seg][data-g]')?.dataset.g||'',g=byGroup.get(String(gid)),head=card.querySelector('.head');if(!g||!head)return;const phone=String(g.contact||'').trim();let tag=head.querySelector('.zr-phone-tag');if(!phone){tag?.remove();return}if(!tag){tag=document.createElement('a');tag.className='tag zr-phone-tag'}const org=head.querySelector('.org');if(org&&org.nextElementSibling!==tag)org.insertAdjacentElement('afterend',tag);else if(!org&&!tag.parentElement)head.prepend(tag);tag.href='tel:'+tel(phone);tag.textContent='☎ '+phone;tag.title='예약자 전화번호'});
  document.querySelectorAll('.seg[data-seg]').forEach(el=>{const g=byGroup.get(String(el.dataset.g||'')),s=(g?.segments||[]).find(x=>String(x.id)===String(el.dataset.seg||'')),b=el.querySelector('b');if(!s||!b)return;const l=label(s),w=el.getBoundingClientRect().width;b.textContent=w>0&&w<54?short(s,l):l;el.style.setProperty('background',color(s),'important');el.classList.toggle('zr-short-seg',w>0&&w<54);el.classList.toggle('zr-tight-time',w>0&&w<74);const small=el.querySelector('small');if(small)small.textContent=`${s.start||''}~${s.end||''}`;el.title=l+` ${s.start||''}~${s.end||''}`});
  const legend=document.querySelector('.legend');if(legend){[['f4','.f4'],['f5','.f5'],['meal','.mealC'],['play','.play']].forEach(([type,sel])=>{const el=legend.querySelector(sel),c=cat(type);if(el){el.textContent=c.name;el.style.background=c.color}});legend.querySelectorAll('[data-custom-legend]').forEach(x=>x.remove());[...state.catalog.entries()].filter(([type])=>String(type).startsWith('custom_')).forEach(([type,c])=>{const s=document.createElement('span');s.dataset.customLegend=type;s.textContent=c.name;s.style.background=c.color;legend.appendChild(s)})}
  if(state.activeContentGid&&state.contentState){[...document.querySelectorAll('#contentRows .contentRow')].forEach((row,i)=>{const s=state.contentState.changed?.[i],name=row.querySelector('.contentName');if(!s||!name)return;name.textContent=label(s);name.style.setProperty('background',color(s),'important');name.dataset.zrCustomType=s.type||''});['originalTimeline','changedTimeline'].forEach(tid=>{const box=$(tid),arr=tid==='originalTimeline'?state.contentState.original:state.contentState.changed;if(!box)return;[...box.querySelectorAll('.seg')].forEach((el,i)=>{const s=arr?.[i],b=el.querySelector('b');if(!s||!b)return;const l=label(s),w=el.getBoundingClientRect().width;b.textContent=w>0&&w<54?short(s,l):l;el.style.setProperty('background',color(s),'important');el.title=`${l} ${s.start||''}~${s.end||''}`})})}
}
export function injectDisplayStyle(){if($('zrScheduleDisplayUnifiedStyle'))return;const s=document.createElement('style');s.id='zrScheduleDisplayUnifiedStyle';s.textContent='.zr-phone-tag{background:#eef6f1!important;color:#2f6b4f!important;text-decoration:none;white-space:nowrap;flex:none}.zr-quick-time{appearance:none;-webkit-appearance:none;border:0!important;font-weight:400!important;line-height:1!important;touch-action:manipulation;pointer-events:auto!important;position:relative;z-index:2}.zr-quick-time.has{font-weight:800!important}.seg.zr-short-seg{padding-left:2px!important;padding-right:2px!important;text-align:center!important;align-items:center!important}.seg.zr-short-seg b{font-size:9px!important;letter-spacing:-.5px!important;text-align:center!important;width:100%}#contentRows .contentName[data-zr-custom-type]{border:1px solid rgba(31,42,35,.08)}#list .timeline{height:58px!important}#list .seg{top:5px!important;height:46px!important;padding:3px 4px!important}#list .seg b{font-size:10px!important;line-height:1.05!important}#list .seg small{display:block!important;font-size:8px!important;font-weight:800!important;line-height:1.05!important;margin-top:5px!important;color:#45564b!important}#list .seg.zr-tight-time small{font-size:7px!important;letter-spacing:-.35px!important}#ruler{height:27px!important}#ruler .tick{top:8px!important;font-size:8px!important}@media(max-width:430px){#list .head{flex-wrap:wrap!important;align-items:flex-start!important;overflow:visible!important;padding-top:7px!important;padding-bottom:7px!important}#list .head .org{flex:1 0 100%!important;max-width:100%!important;white-space:normal!important;overflow:visible!important;text-overflow:clip!important;line-height:1.3!important;font-size:12px!important;word-break:keep-all!important;overflow-wrap:anywhere!important;padding-right:2px!important}#list .head .tag,#list .head .detail{margin-top:1px!important}}';document.head.appendChild(s)}
