(()=>{
const BASE_PRICE=15000;
const KR_HOLIDAYS_2026=new Set([
'2026-01-01','2026-02-16','2026-02-17','2026-02-18','2026-03-01','2026-03-02',
'2026-05-05','2026-05-24','2026-05-25','2026-06-03','2026-06-06','2026-08-15','2026-08-17',
'2026-09-24','2026-09-25','2026-09-26','2026-10-03','2026-10-05','2026-10-09','2026-12-25'
]);
const isHoliday=date=>KR_HOLIDAYS_2026.has(date)||['01-01','03-01','05-05','06-06','08-15','10-03','10-09','12-25'].includes(String(date||'').slice(5));
const vendors=()=>[{id:'self',name:'자체',groupPrice:BASE_PRICE,ticketFeeType:'flat',ticketFeeValue:0,cafeFeeType:'flat',cafeFeeValue:0},...(settings().outsourcingVendors||[]).filter(v=>String(v.name||'').trim()).slice(0,10)];
const vendorById=id=>vendors().find(v=>v.id===id)||null;
const selectedVendorId=b=>b.outsourcingVendorId||b.settlement?.vendorId||'self';
const snapshot=v=>({id:v.id,name:v.name,groupPrice:Number(v.groupPrice||0),ticketFeeType:v.ticketFeeType==='percent'?'percent':'flat',ticketFeeValue:Number(v.ticketFeeValue||0),cafeFeeType:v.cafeFeeType==='percent'?'percent':'flat',cafeFeeValue:Number(v.cafeFeeValue||0)});
const fee=(amount,type,value)=>Number(amount||0)<=0?0:(type==='percent'?Math.round(Number(amount||0)*Number(value||0)/100):Math.round(Number(value||0)));
const freeChap=(paid,chap)=>Math.min(Math.floor(Math.max(0,Number(paid||0))/5),Math.max(0,Number(chap||0)));
const addMin=(start,dur)=>{const m=toMin(start);return m==null||!dur?'':toTime(m+Number(dur||0))};
function recalcSettlement(b,v){
if(!b.settlement)return;
const st=b.settlement,s=snapshot(v),paid=Number(st.actualPaidCount||0),paidChap=Number(st.actualPaidChaperone||0),cafe=Number(st.actualCafeAmount||0),ticket=(paid+paidChap)*s.groupPrice;
Object.assign(st,{vendorId:v.id,vendorSnapshot:s,ticketUnitPrice:s.groupPrice,ticketAmount:ticket,totalActualSales:ticket+cafe,ticketFee:v.id==='self'?0:fee(ticket,s.ticketFeeType,s.ticketFeeValue),cafeFee:v.id==='self'?0:fee(cafe,s.cafeFeeType,s.cafeFeeValue),savedAt:new Date().toISOString()});
st.totalFee=st.ticketFee+st.cafeFee;
}
window.saveBookingVendor=function(id,vendorId){
if(!adminGuard())return;const v=vendorById(vendorId),bs=bookings(),b=bs.find(x=>x.id===id);if(!v||!b)return toast('업체 또는 예약 정보를 찾지 못했습니다.');
b.outsourcingVendorId=v.id;b.outsourcingVendorSnapshot=snapshot(v);recalcSettlement(b,v);setStore('zr_bookings',bs);addActivity('vendor',b,`결제 구분 변경 · ${v.name}`);toast(`${v.name}으로 설정했습니다.`);renderOutsourcingPayments();
if(!$('adminBookingDetailModal').classList.contains('hidden'))openAdminBookingDetail(id);if(!$('dayDetailModal').classList.contains('hidden'))openDay(b.date);
};
function vendorBox(b){
const sel=selectedVendorId(b),r=vendors().map(v=>`<label class="zr2-radio ${sel===v.id?'on':''}"><input type="radio" name="v_${escapeHtml(b.id)}" value="${escapeHtml(v.id)}" ${sel===v.id?'checked':''} onchange="saveBookingVendor('${b.id}',this.value)"><span>${escapeHtml(v.name)}${v.id!=='self'?` <small>${money(v.groupPrice)}</small>`:''}</span></label>`).join('');
return `<div class="zr2-vendor"><div class="help"><b>결제 구분 / 아웃소싱 업체</b> · 하나만 선택</div><div class="zr2-radios">${r}</div></div>`;
}
function settlementHtml(b){
const st=b.settlement||{},v=vendorById(selectedVendorId(b))||vendorById('self'),ap=st.actualPaidCount??b.paidCount??0,af=st.actualFreeChaperone??b.freeChaperone??0,ac=st.actualPaidChaperone??b.paidChaperone??0,cafe=st.actualCafeAmount??0;
return `<div class="calc zr2-settle" data-id="${escapeHtml(b.id)}" style="margin-top:14px"><input type="radio" data-field="vendor" value="${escapeHtml(v.id)}" checked hidden><div class="row"><div><b>실제 결제 / 정산 입력</b><div class="help">접수일 ${dateTimeText(b.createdAt)} · 방문일 ${b.date}</div></div><span class="status confirmed">${escapeHtml(v.name)}</span></div><div class="grid2" style="margin-top:12px"><div><label>실제 유료인원</label><input type="number" min="0" data-field="actualPaid" value="${ap}" oninput="zr2Preview('${b.id}',this)"></div><div><label>실제 무료인솔</label><input type="number" min="0" data-field="actualFree" value="${af}" oninput="zr2Preview('${b.id}',this)"></div><div><label>실제 유료인솔</label><input type="number" min="0" data-field="actualPaidChap" value="${ac}" oninput="zr2Preview('${b.id}',this)"></div><div><label>카페 실제 결제금액</label><input type="number" min="0" step="100" data-field="actualCafe" value="${cafe}" oninput="zr2Preview('${b.id}',this)"></div></div><div class="calc" data-preview style="margin-top:10px"></div><div style="display:flex;justify-content:flex-end;margin-top:10px"><button class="btn-primary" onclick="zr2SaveSettlement('${b.id}',this)">실제 결제 저장</button></div></div>`;
}
window.zr2Preview=function(id,el){
const root=el.closest('.zr2-settle'),b=bookings().find(x=>x.id===id);if(!root||!b)return;const v=vendorById(selectedVendorId(b))||vendorById('self'),paid=Number(root.querySelector('[data-field="actualPaid"]').value||0),pc=Number(root.querySelector('[data-field="actualPaidChap"]').value||0),cafe=Number(root.querySelector('[data-field="actualCafe"]').value||0),ticket=(paid+pc)*Number(v.groupPrice||0);root.querySelector('[data-preview]').innerHTML=`<b>실제 매출 계산</b><br>결제 구분 <b>${escapeHtml(v.name)}</b> · 적용 단체가 <b>${money(v.groupPrice)}</b><br>매표 매출 <b>${money(ticket)}</b> · 카페 실제 결제 <b>${money(cafe)}</b><br><span class="money">실제 총매출 ${money(ticket+cafe)}</span>`;
};
window.zr2SaveSettlement=function(id,el){
if(!adminGuard())return;const root=el.closest('.zr2-settle'),bs=bookings(),b=bs.find(x=>x.id===id);if(!root||!b)return;const v=vendorById(selectedVendorId(b))||vendorById('self'),s=snapshot(v),paid=Number(root.querySelector('[data-field="actualPaid"]').value||0),fr=Number(root.querySelector('[data-field="actualFree"]').value||0),pc=Number(root.querySelector('[data-field="actualPaidChap"]').value||0),cafe=Number(root.querySelector('[data-field="actualCafe"]').value||0),ticket=(paid+pc)*s.groupPrice,ticketFee=v.id==='self'?0:fee(ticket,s.ticketFeeType,s.ticketFeeValue),cafeFee=v.id==='self'?0:fee(cafe,s.cafeFeeType,s.cafeFeeValue);
b.outsourcingVendorId=v.id;b.outsourcingVendorSnapshot=s;b.settlement={vendorId:v.id,vendorSnapshot:s,actualPaidCount:paid,actualFreeChaperone:fr,actualPaidChaperone:pc,actualCafeAmount:cafe,ticketUnitPrice:s.groupPrice,ticketAmount:ticket,totalActualSales:ticket+cafe,ticketFee,cafeFee,totalFee:ticketFee+cafeFee,savedAt:new Date().toISOString()};setStore('zr_bookings',bs);addActivity('settlement',b,`실제 결제 저장 · ${v.name}`);toast('실제 결제 내역을 저장했습니다.');renderOutsourcingPayments();if(!$('dayDetailModal').classList.contains('hidden'))openDay(b.date);if(!$('adminBookingDetailModal').classList.contains('hidden'))openAdminBookingDetail(id);
};
const actionButtons=b=>b.status==='pending'?`<div class="top-actions" style="margin-top:14px"><button class="btn-primary" onclick="requestBookingStatus('${b.id}','confirmed')">예약 확정</button><button class="btn-soft" onclick="openAdminEditBooking('${b.id}')">예약 수정</button><button class="btn-gray" onclick="requestBookingStatus('${b.id}','cancelled')">취소 처리</button></div>`:b.status==='confirmed'?`<div class="top-actions" style="margin-top:14px"><button class="btn-soft" onclick="openAdminEditBooking('${b.id}')">예약 수정</button><button class="btn-danger" onclick="requestBookingStatus('${b.id}','cancelled')">예약 취소 처리</button></div>`:'';
function detailHtml(b){
const mt={lunchbox:'도시락 지참',cafe:'내부 카페 주문',none:'식사 없음'}[b.mealType]||'-',play=(b.playUse==='no'||!b.playStart)?'이용 안 함':`${b.playStart}~${b.playEnd}`,items=(b.cafe?.items||[]).map(x=>`${escapeHtml(x.name)} × ${x.qty}`).join('<br>');
return `<h2>${escapeHtml(b.orgName)}</h2><div class="row"><div class="help">예약번호 ${b.id}<br>접수 ${dateTimeText(b.createdAt)}</div>${adminStatusBadge(b.status)}</div><div class="detail-grid"><div><b>예약일</b><br>${b.date}</div><div><b>예약자</b><br>${escapeHtml(b.managerName)}<br>${escapeHtml(b.contact)}</div><div><b>입장 / 퇴장</b><br>${b.entryTime} ~ ${b.exitTime}</div><div><b>놀이터</b><br>${play}</div><div><b>인원</b><br>유료 ${b.paidCount} / 인솔 ${b.chaperoneCount}<br>무료 ${b.freeChaperone} / 유료인솔 ${b.paidChaperone}</div><div><b>금액</b><br>${money(b.totalAmount)}<br>현장결제</div><div><b>식사</b><br>${mt}${b.mealStart?`<br>${b.mealStart}~${b.mealEnd}`:''}</div><div><b>단체 유형</b><br>${escapeHtml(b.groupType||'-')}</div></div>${items?`<div class="calc" style="margin-top:12px"><b>카페 주문</b><br>${items}</div>`:''}${b.notes?`<div class="calc" style="margin-top:12px"><b>특이사항</b><br>${escapeHtml(b.notes)}</div>`:''}${b.status==='cancelled'?`<div class="calc" style="margin-top:12px"><b>취소 정보</b><br>${cancellationSourceText(b)} · ${dateTimeText(b.cancelledAt)}</div>`:''}${!['cancelled','rejected'].includes(b.status)?vendorBox(b):''}${actionButtons(b)}${b.status==='confirmed'?settlementHtml(b):''}`;
}
adminBookingDetailHtml=detailHtml;
window.openAdminBookingDetail=openAdminBookingDetail=function(id){if(!adminGuard())return;const b=bookings().find(x=>x.id===id);if(!b)return toast('예약 정보를 찾지 못했습니다.');$('adminBookingDetailContent').innerHTML=detailHtml(b);openModal('adminBookingDetailModal');const r=$('adminBookingDetailContent').querySelector('.zr2-settle');if(r)zr2Preview(id,r.querySelector('[data-field="actualPaid"]'));};
renderAdmin=function(){
if(!adminGuard(false))return;const ym=$('adminMonth').value||monthOptions()[0].key;$('adminMonth').value=ym;const bs=activeBookings().filter(b=>monthKey(b.date)===ym);$('kpiTeams').textContent=bs.length+'팀';$('kpiPeople').textContent=bs.reduce((s,b)=>s+totalPeople(b),0)+'명';$('kpiPending').textContent=bs.filter(b=>b.status==='pending').length+'건';const [y,m]=ym.split('-').map(Number),first=new Date(y,m-1,1).getDay(),last=new Date(y,m,0).getDate(),s=settings();if($('autoClose'))$('autoClose').checked=s.autoCloseLimit>0;$('bookingOpenStart').value=s.bookingStart||'';$('bookingOpenEnd').value=s.bookingEnd||'';let html=['일','월','화','수','목','금','토'].map((x,i)=>`<div class="weekday ${i===0?'zr2-red':i===6?'zr2-blue':''}">${x}</div>`).join('');for(let i=0;i<first;i++)html+='<div></div>';
for(let d=1;d<=last;d++){const date=validDateStr(y,m,d),wd=new Date(y,m-1,d).getDay(),hol=isHoliday(date),dayBs=activeBookings().filter(b=>b.date===date),closed=isDateClosed(date),ppl=dayBs.reduce((z,b)=>z+totalPeople(b),0),pending=dayBs.filter(b=>b.status==='pending').length,cls=['day',closed?'closed':'',wd===6?'zr2-sat':'',wd===0?'zr2-sun':'',hol?'zr2-hol':''].filter(Boolean).join(' ');html+=`<div class="${cls}"><div class="num" style="display:flex;justify-content:space-between;gap:6px;align-items:center;flex-wrap:wrap"><span class="${hol||wd===0?'zr2-red':wd===6?'zr2-blue':''}">${d}일${hol?'<small class="zr2-holiday"> 공휴일</small>':''}</span><span style="display:flex;gap:5px;align-items:center;flex-wrap:wrap">${pending?`<span class="status pending">접수 ${pending}건</span>`:''}${closed?'<span class="status rejected">마감</span>':''}</span></div><div class="meta">${dayBs.length}팀 / ${ppl}명</div><button class="btn-soft" onclick="openDay('${date}')">자세히</button></div>`;}
$('adminCalendar').innerHTML=html;renderExtendedSettings();
};
window.openDay=function(date){
if(!adminGuard())return;const all=bookings().filter(b=>b.date===date),s=settings(),manual=s.manualClosed.includes(date),limit=Number(s.autoCloseLimit||0),override=s.autoCloseOverrideOpen.includes(date),reached=limit>0&&bookingCount(date)>=limit;let html=`<div class="row"><div><h2>${date} 예약 상세</h2><div class="help">${activeBookings().filter(b=>b.date===date).length}팀 / ${activeBookings().filter(b=>b.date===date).reduce((x,b)=>x+totalPeople(b),0)}명</div></div><button class="btn-primary" onclick="openAdminQuickBooking('${date}')">+ 관리자 예약 등록</button></div><div class="top-actions" style="margin:12px 0"><button class="${manual?'btn-soft':'btn-danger'}" onclick="toggleManualClose('${date}')">${manual?'수동 마감 해제':'수동 마감'}</button>${reached?`<button class="${override?'btn-gray':'btn-soft'}" onclick="toggleAutoCloseOverride('${date}')">${override?'자동마감 다시 적용':'자동마감 해제'}</button>`:''}</div>${reached&&override?`<div class="help warn">이 날짜는 ${limit}팀 이상이지만 관리자가 자동마감을 해제한 상태입니다.</div>`:''}`;if(!all.length)html+='<div class="help">예약이 없습니다.</div>';
all.forEach(b=>{const st=b.status==='pending'?'<span class="status pending">접수</span>':b.status==='confirmed'?'<span class="status confirmed">확정</span>':b.status==='cancelled'?'<span class="status rejected">취소</span>':'<span class="status rejected">거절</span>',mt={lunchbox:'도시락',cafe:'카페 주문',none:'식사 없음'}[b.mealType]||'-';html+=`<div class="booking-item"><div class="row"><div><b>${escapeHtml(b.orgName)}</b><div class="help">${escapeHtml(b.groupType||'-')}<br>접수 ${dateTimeText(b.createdAt)}</div></div>${st}</div><div class="detail-grid"><div>유료 ${b.paidCount} / 인솔 ${b.chaperoneCount}<br>무료 ${b.freeChaperone} / 유료인솔 ${b.paidChaperone}</div><div>동물원 ${b.entryTime}~${b.exitTime}</div><div>식사 ${mt}${b.mealStart?`<br>${b.mealStart}~${b.mealEnd}`:''}</div><div>놀이터 ${(b.playUse==='no'||!b.playStart)?'이용 안 함':`${b.playStart}~${b.playEnd}`}</div><div>예약자 ${escapeHtml(b.managerName)}<br>${escapeHtml(b.contact)}</div><div>예약금액 ${money(b.totalAmount)}<br>현장결제</div></div>${!['cancelled','rejected'].includes(b.status)?vendorBox(b):''}${actionButtons(b)}${b.status==='confirmed'?settlementHtml(b):''}</div>`;});$('dayDetailContent').innerHTML=html;openModal('dayDetailModal');$('dayDetailContent').querySelectorAll('.zr2-settle').forEach(r=>zr2Preview(r.dataset.id,r.querySelector('[data-field="actualPaid"]')));
};
function formHtml(prefix,b={},date=''){
const gp=['유치원, 어린이집','초등학교','중학교','고등학교','복지기관','기타단체','기업'],meal=b.mealType||'none',play=b.playUse||'no',vid=selectedVendorId(b);
return `<div class="grid2"><div><label>단체명</label><input id="${prefix}Org" value="${escapeHtml(b.orgName||'')}"></div><div><label>단체 유형</label><select id="${prefix}GroupType">${gp.map(x=>`<option ${x===(b.groupType||'기타단체')?'selected':''}>${x}</option>`).join('')}</select></div><div><label>예약자명</label><input id="${prefix}Manager" value="${escapeHtml(b.managerName||'')}"></div><div><label>연락처</label><input id="${prefix}Contact" value="${escapeHtml(b.contact||'')}"></div><div><label>이메일</label><input id="${prefix}Email" value="${escapeHtml(b.email||'')}"></div><div><label>방문일</label><input type="date" id="${prefix}Date" value="${b.date||date||''}"></div><div><label>유료인원</label><input type="number" min="0" id="${prefix}Paid" value="${b.paidCount??15}"></div><div><label>인솔자</label><input type="number" min="0" id="${prefix}Chaperone" value="${b.chaperoneCount??0}"></div><div><label>입장시간</label><input type="time" step="1800" id="${prefix}Entry" value="${b.entryTime||'10:30'}"></div><div><label>퇴장시간</label><input type="time" step="1800" id="${prefix}Exit" value="${b.exitTime||'13:30'}"></div><div><label>식사</label><select id="${prefix}MealType"><option value="none" ${meal==='none'?'selected':''}>식사 없음</option><option value="lunchbox" ${meal==='lunchbox'?'selected':''}>도시락</option><option value="cafe" ${meal==='cafe'?'selected':''}>카페 주문</option></select></div><div><label>예약 카페금액</label><input type="number" min="0" step="100" id="${prefix}CafeAmount" value="${b.cafe?.amount||0}"></div><div><label>식사 시작</label><input type="time" step="900" id="${prefix}MealStart" value="${b.mealStart||''}"></div><div><label>식사 시간(분)</label><input type="number" min="0" step="15" id="${prefix}MealDuration" value="${b.mealDuration||0}"></div><div><label>놀이터</label><select id="${prefix}PlayUse"><option value="no" ${play==='no'?'selected':''}>이용 안 함</option><option value="yes" ${play==='yes'?'selected':''}>이용함</option></select></div><div><label>놀이터 시작</label><input type="time" step="1800" id="${prefix}PlayStart" value="${b.playStart||''}"></div><div><label>놀이터 시간(분)</label><input type="number" min="0" step="30" id="${prefix}PlayDuration" value="${b.playDuration||0}"></div><div><label>결제 구분</label><select id="${prefix}Vendor">${vendors().map(v=>`<option value="${escapeHtml(v.id)}" ${vid===v.id?'selected':''}>${escapeHtml(v.name)}${v.id!=='self'?` · ${money(v.groupPrice)}`:''}</option>`).join('')}</select></div></div><div style="margin-top:12px"><label>특이사항</label><textarea rows="3" id="${prefix}Notes">${escapeHtml(b.notes||'')}</textarea></div>`;
}
function vals(prefix){const q=n=>$(prefix+n),paid=Number(q('Paid').value||0),chap=Number(q('Chaperone').value||0),fr=freeChap(paid,chap),pc=Math.max(0,chap-fr),meal=q('MealType').value,play=q('PlayUse').value,ms=meal==='none'?'':q('MealStart').value,md=meal==='none'?0:Number(q('MealDuration').value||0),ps=play==='no'?'':q('PlayStart').value,pd=play==='no'?0:Number(q('PlayDuration').value||0);return {org:q('Org').value.trim(),group:q('GroupType').value,manager:q('Manager').value.trim(),contact:q('Contact').value.trim(),email:q('Email').value.trim(),date:q('Date').value,paid,chap,fr,pc,entry:q('Entry').value,exit:q('Exit').value,meal,ms,md,me:addMin(ms,md),play,ps,pd,pe:addMin(ps,pd),cafe:meal==='cafe'?Number(q('CafeAmount').value||0):0,vendor:q('Vendor').value||'self',notes:q('Notes').value.trim()};}
function validate(v,exclude=''){if(!v.org||!v.manager||!v.contact)return '단체명, 예약자명, 연락처를 입력해주세요.';if(!v.date)return '방문일을 입력해주세요.';if(!v.entry||!v.exit||toMin(v.exit)<=toMin(v.entry))return '입장·퇴장시간을 확인해주세요.';if(v.meal!=='none'){if(!v.ms||!v.md)return '식사시간을 입력해주세요.';if(toMin(v.ms)<toMin(v.entry)||toMin(v.me)>toMin(v.exit))return '식사시간을 방문시간 안으로 조정해주세요.';}if(v.play==='yes'){if(!v.ps||!v.pd)return '놀이터 이용시간을 입력해주세요.';if(toMin(v.pe)>toMin(v.exit))return '놀이터 종료시간이 퇴장시간을 넘을 수 없습니다.';if(settings().playgroundLimitEnabled!==false){const taken=takenPlaySlots(v.date,exclude);for(let t=toMin(v.ps);t<toMin(v.pe);t+=30)if(taken.has(toTime(t)))return '선택한 놀이터 시간은 다른 단체가 사용 중입니다.';}}if(v.ms&&v.ps&&sameIntervalOverlap(toMin(v.ms),toMin(v.me),toMin(v.ps),toMin(v.pe)))return '식사시간과 놀이터시간이 겹칩니다.';return '';}
window.openAdminEditBooking=function(id){if(!adminGuard())return;const b=bookings().find(x=>x.id===id);if(!b)return toast('예약 정보를 찾지 못했습니다.');$('zr2EditId').value=id;$('zr2EditBody').innerHTML=formHtml('zr2e',b);openModal('zr2EditModal');};
function saveEdit(){const id=$('zr2EditId').value,bs=bookings(),b=bs.find(x=>x.id===id);if(!b)return;const v=vals('zr2e'),err=validate(v,id);if(err)return toast(err);const ven=vendorById(v.vendor)||vendorById('self'),entry=(v.paid+v.pc)*BASE_PRICE;Object.assign(b,{orgName:v.org,groupType:v.group,managerName:v.manager,contact:v.contact,email:v.email,date:v.date,paidCount:v.paid,chaperoneCount:v.chap,freeChaperone:v.fr,paidChaperone:v.pc,entryTime:v.entry,exitTime:v.exit,entryAmount:entry,mealType:v.meal,mealStart:v.ms,mealDuration:v.md,mealEnd:v.me,playUse:v.play,playStart:v.ps,playDuration:v.pd,playEnd:v.pe,notes:v.notes,totalAmount:entry+v.cafe,outsourcingVendorId:ven.id,outsourcingVendorSnapshot:snapshot(ven),statusUpdatedAt:new Date().toISOString()});b.cafe=v.meal==='cafe'?{...(b.cafe||{}),items:b.cafe?.items||[],amount:v.cafe}:{items:[],amount:0};recalcSettlement(b,ven);setStore('zr_bookings',bs);addActivity('edited',b,'관리자 예약 정보 수정');closeModal('zr2EditModal');toast('예약 내용을 수정했습니다.');renderAdmin();renderActivity();renderOutsourcingPayments();if(!$('dayDetailModal').classList.contains('hidden'))openDay(b.date);if(!$('adminBookingDetailModal').classList.contains('hidden'))openAdminBookingDetail(id);}
window.openAdminQuickBooking=function(date=''){if(!adminGuard())return;let d=date;if(!d){const ym=$('adminMonth').value||monthOptions()[0].key,n=new Date(),today=validDateStr(n.getFullYear(),n.getMonth()+1,n.getDate());d=monthKey(today)===ym?today:`${ym}-01`;}$('zr2QuickBody').innerHTML=formHtml('zr2q',{},d);openModal('zr2QuickModal');};
function saveQuick(){const v=vals('zr2q'),err=validate(v);if(err)return toast(err);const ven=vendorById(v.vendor)||vendorById('self'),now=new Date().toISOString(),entry=(v.paid+v.pc)*BASE_PRICE,b={id:'B'+Date.now(),createdAt:now,statusUpdatedAt:now,status:'confirmed',confirmedAt:now,createdByAdmin:true,date:v.date,groupType:v.group,paidCount:v.paid,chaperoneCount:v.chap,freeChaperone:v.fr,paidChaperone:v.pc,entryAmount:entry,mealType:v.meal,entryTime:v.entry,exitTime:v.exit,cafe:v.meal==='cafe'?{items:[],amount:v.cafe}:{items:[],amount:0},mealStart:v.ms,mealDuration:v.md,mealEnd:v.me,playUse:v.play,playStart:v.ps,playDuration:v.pd,playEnd:v.pe,orgName:v.org,managerName:v.manager,contact:v.contact,email:v.email,notes:v.notes,totalAmount:entry+v.cafe,outsourcingVendorId:ven.id,outsourcingVendorSnapshot:snapshot(ven)};const bs=bookings();bs.push(b);setStore('zr_bookings',bs);addActivity('submitted',b,'관리자 전화 예약 등록');addActivity('confirmed',b,'관리자 예약 확정');closeModal('zr2QuickModal');toast('관리자 예약을 등록했습니다.');renderAdmin();renderActivity();renderOutsourcingPayments();if(!$('dayDetailModal').classList.contains('hidden'))openDay(b.date);}
function assigned(b){const id=b.settlement?.vendorId||b.outsourcingVendorId;if(!id||id==='self')return null;return b.settlement?.vendorSnapshot||b.outsourcingVendorSnapshot||vendorById(id)||{id,name:id};}
function refreshVendorFilter(){const el=$('outsourceVendorFilter');if(!el)return;const old=el.value,map=new Map((settings().outsourcingVendors||[]).filter(v=>v.name).map(v=>[v.id,v.name]));bookings().forEach(b=>{const v=assigned(b);if(v&&!map.has(v.id))map.set(v.id,v.name||v.id)});el.innerHTML='<option value="">전체 업체</option>'+[...map].map(([id,name])=>`<option value="${escapeHtml(id)}">${escapeHtml(name)}</option>`).join('');if([...el.options].some(o=>o.value===old))el.value=old;}
window.renderOutsourcingPayments=function(){if(!$('tab-outsourcing'))return;refreshVendorFilter();const start=$('outsourceStart').value,end=$('outsourceEnd').value,f=$('outsourceVendorFilter')?.value||'',list=bookings().filter(b=>{const v=assigned(b);return v&&(!f||v.id===f)&&(!start||b.date>=start)&&(!end||b.date<=end)}).sort((a,b)=>String(a.date).localeCompare(String(b.date))),done=list.filter(b=>b.settlement&&b.settlement.vendorId!=='self'),tt=done.reduce((s,b)=>s+Number(b.settlement.ticketAmount||0),0),tc=done.reduce((s,b)=>s+Number(b.settlement.actualCafeAmount||0),0),tf=done.reduce((s,b)=>s+Number(b.settlement.totalFee||0),0);$('outsourceKpiTeams').textContent=`${list.length}건 (정산 ${done.length})`;$('outsourceKpiTicket').textContent=money(tt);$('outsourceKpiCafe').textContent=money(tc);$('outsourceKpiFee').textContent=money(tf);$('outsourceList').innerHTML=list.length?list.map(b=>{const v=assigned(b),st=b.settlement;if(!st)return `<div class="booking-item"><div class="row"><div><b>${escapeHtml(b.orgName)}</b><div class="help">접수 ${dateTimeText(b.createdAt)} · 방문 ${b.date}</div></div><span class="status pending">${escapeHtml(v.name)} · 실제결제 미입력</span></div><div class="help" style="margin-top:8px">실제 결제값을 입력하면 정산금액이 계산됩니다.</div></div>`;const s=st.vendorSnapshot||v,tr=s.ticketFeeType==='percent'?`${s.ticketFeeValue}%`:`건당 ${money(s.ticketFeeValue||0)}`,cr=s.cafeFeeType==='percent'?`${s.cafeFeeValue}%`:`건당 ${money(s.cafeFeeValue||0)}`;return `<div class="booking-item"><div class="row"><div><b>${escapeHtml(b.orgName)}</b><div class="help">접수 ${dateTimeText(b.createdAt)} · 방문 ${b.date}</div></div><span class="status confirmed">${escapeHtml(s.name)}</span></div><div class="detail-grid"><div><b>실제 인원</b><br>유료 ${st.actualPaidCount||0} / 무료인솔 ${st.actualFreeChaperone||0} / 유료인솔 ${st.actualPaidChaperone||0}</div><div><b>적용 단체가</b><br>${money(st.ticketUnitPrice||0)}</div><div><b>매표 매출</b><br>${money(st.ticketAmount||0)}</div><div><b>매표 수수료</b><br>${money(st.ticketFee||0)}<br><span class="help">${tr}</span></div><div><b>카페 매출</b><br>${money(st.actualCafeAmount||0)}</div><div><b>카페 수수료</b><br>${money(st.cafeFee||0)}<br><span class="help">${cr}</span></div></div><div class="calc" style="margin-top:10px"><b>총 수수료 지급액 ${money(st.totalFee||0)}</b> · 실제 총매출 ${money(st.totalActualSales||0)}</div></div>`;}).join(''):'<div class="help">조회 조건에 해당하는 아웃소싱 예약이 없습니다.</div>';};
function install2(){
const style=document.createElement('style');style.textContent=`.zr2-radios{display:flex;gap:7px;flex-wrap:wrap;margin-top:7px}.zr2-radio{display:flex;align-items:center;gap:5px;padding:8px 9px;border:1px solid var(--line);border-radius:10px;background:#fff;font-size:13px;cursor:pointer}.zr2-radio.on{background:#f0f8f3;border-color:#6b9c7d}.zr2-radio input{width:auto}.zr2-vendor{width:min(640px,100%);box-sizing:border-box;margin:14px 0 0 auto;padding:11px;border:1px solid var(--line);border-radius:13px;background:#f8faf8}#adminCalendar .zr2-sat{background:#f2f7ff;border-color:#d5e2f4}#adminCalendar .zr2-sun,#adminCalendar .zr2-hol{background:#fff3f3;border-color:#efd3d3}.zr2-blue{color:#3568aa!important}.zr2-red{color:#bd4b4b!important}.zr2-holiday{font-size:10px;font-weight:800}.zr2-modal .modal-card{width:min(760px,100%)}@media(max-width:800px){.zr2-radios{display:grid;grid-template-columns:1fr 1fr}.zr2-modal .grid2{grid-template-columns:1fr}}`;document.head.appendChild(style);
if($('adminCreateBooking'))$('adminCreateBooking').onclick=()=>openAdminQuickBooking('');
const edit=document.createElement('div');edit.className='modal hidden zr2-modal';edit.id='zr2EditModal';edit.innerHTML='<div class="modal-card"><h2>예약 내용 수정</h2><input type="hidden" id="zr2EditId"><div id="zr2EditBody"></div><div class="modal-actions"><button class="btn-gray" id="zr2EditCancel">취소</button><button class="btn-primary" id="zr2EditSave">수정 저장</button></div></div>';document.body.appendChild(edit);$('zr2EditCancel').onclick=()=>closeModal('zr2EditModal');$('zr2EditSave').onclick=saveEdit;
const quick=document.createElement('div');quick.className='modal hidden zr2-modal';quick.id='zr2QuickModal';quick.innerHTML='<div class="modal-card"><h2>관리자 빠른 예약 등록</h2><div class="help" style="margin-bottom:12px">전화 받으면서 바로 입력하는 관리자 전용 간편 등록입니다. 저장하면 즉시 예약 확정으로 등록됩니다.</div><div id="zr2QuickBody"></div><div class="modal-actions"><button class="btn-gray" id="zr2QuickCancel">취소</button><button class="btn-primary" id="zr2QuickSave">예약 등록</button></div></div>';document.body.appendChild(quick);$('zr2QuickCancel').onclick=()=>closeModal('zr2QuickModal');$('zr2QuickSave').onclick=saveQuick;
const sec=$('tab-outsourcing');if(sec){const first=sec.querySelector('.card');first.innerHTML=`<h2>아웃소싱 결제대금</h2><div class="grid3"><div><label>업체</label><select id="outsourceVendorFilter"><option value="">전체 업체</option></select></div><div><label>방문일 시작</label><input type="date" id="outsourceStart"></div><div><label>방문일 종료</label><input type="date" id="outsourceEnd"></div></div><div style="display:flex;justify-content:flex-end;margin-top:10px"><button class="btn-primary" id="outsourceSearch">조회하기</button></div><div class="help" style="margin-top:8px">업체별로 조회할 수 있으며 실제 결제 미입력 예약도 함께 표시됩니다.</div>`;const n=new Date(),f=x=>String(x).padStart(2,'0');$('outsourceStart').value=`${n.getFullYear()}-${f(n.getMonth()+1)}-01`;$('outsourceEnd').value=`${n.getFullYear()}-${f(n.getMonth()+1)}-${f(n.getDate())}`;$('outsourceSearch').onclick=renderOutsourcingPayments;$('outsourceVendorFilter').onchange=renderOutsourcingPayments;refreshVendorFilter();}
const outBtn=$('outsourceTabBtn');if(outBtn){document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>outBtn.className='btn-gray'));outBtn.addEventListener('click',()=>setTimeout(()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.className='btn-gray');outBtn.className='btn-primary';renderOutsourcingPayments();},0));}
renderAdmin();
}
install2();
})();